### ISSUE TITLE
Multi-display support

### ISSUE THREAD

**Issue by louaybassbouss** [w3c/presentation-api#1]
The current spec considers only one connected display. From my point of view I think it is better to support multiple displays that can be connected to the same Browser. Example: Presentation with slides view on one screen and notes view on another screen and mobile device as input device.

**Comment by mfoltzgoogle** [comment]
This requirement is captured in the current spec under [Media flinging to multiple screens](http://w3c.github.io/presentation-api/#media-flinging-to-multiple-screens).  The spec changes required to implement it are captured in issues #32, #40, and #19.

Louay, do you want to leave this issue open or would it be okay to close it and track work in those more specific issues?

**Comment by louaybassbouss** [comment]
Agree please close it, the other issues are more specific as you mentioned

On 10 Feb 2015, at 03:05, Mark Foltz <notifications@github.com<mailto:notifications@github.com>> wrote:


This requirement is captured in the current spec under Media flinging to multiple screens<http://w3c.github.io/presentation-api/#media-flinging-to-multiple-screens>. The spec changes required to implement it are captured in issues #32<https://github.com/w3c/presentation-api/issues/32>, #40<https://github.com/w3c/presentation-api/issues/40>, and #19<https://github.com/w3c/presentation-api/issues/19>.

Louay, do you want to leave this issue open or would it be okay to close it and track work in those more specific issues?

**Comment by mfoltzgoogle** [comment]
Closing at Louay's request.
