### ISSUE TITLE
Is user permission required to prompt for screen availability information?

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#10]
We do not want to require user permission before disclosing the presence of a presentation display, as it is counter to the initial purpose of improving the user experience.

**Comment by jcdufourd** [comment]
If the page displaying this info is the result of a direct user interaction, then I would think not.
If the page is started by a script and not rendered, then yes.
So I guess my answer is, it depends.

**Comment by mounirlamouri** [comment]
Closing in favour of working on PING feedback.
