### ISSUE TITLE
Update the Status section, note stability per section

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#112]
Specifically, the following statement may cause confusion, since it is rather ambiguous and also somewhat incorrect:

>Most sections are still incomplete or underspecified.

http://w3c.github.io/presentation-api/#sotd

That text was added for the purpose of the First Public Draft publication and
the spec has evolved since significantly. We should instead annotate those sections that are more unstable or incomplete to make it easier for new contributors and implementers to jump in and focus their efforts.

**Comment by tidoust** [comment]
Note the pull request #113 to migrate to the new publication system contains a few updates to the SOTD that removes parts that were very specific to the First Public Working Draft. This can most probably be improved, the updates in the pull request are more focused on making it easy to publish a Working Draft than on the actual prose of the Status of This Document section.

**Comment by mfoltzgoogle** [comment]
I think the current text is an improvement: iit refers the reader to our GitHub repository for open issues, which is the most up to date information.
