### ISSUE TITLE
Spec authoring tool migration

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#116]
[This issue is only relevant to spec editors and participants who do direct spec contributions.]

The Anolis tool this group uses for authoring the Presentation API specification [will not be maintained further][1]. To that end, we should migrate from Anolis to one of the alternatives that are being actively maintained and developed further:

* [Bikeshed][2]
* [ReSpec][3]

Since Anolis will continue to function, there's no urgency to do the migration. We should just not expect new features or bug fixes to land in Anolis unless we maintain the project ourselves.

**Actions:**

- [x] Migrate from Anolis to an anternative tool chosen by the editor(s), @tidoust to help the editor(s) with the migration
- [x] Update [Direct Spec Contributions][4] guidelines accordingly

[1]: https://lists.w3.org/Archives/Public/spec-prod/2015AprJun/0034.html
[2]: https://github.com/tabatkins/bikeshed
[3]: https://www.w3.org/respec/
[4]: https://www.w3.org/wiki/Second_Screen/Work_Mode#Direct_Spec_Contributions

**Comment by mfoltzgoogle** [comment]
I took a look at these two alternatives.  The main differences that I can see:

- ReSpec works directly in the browser (update cycle is edit-reload).  Bikeshed requires a local processing tool and makefile (update cycle is edit-make-reload).
- Publication with ReSpec requires a manual step - saving the generated HTML in a file.  I think this is reasonable.
- ReSpec expects well formed HTML.
- Bikeshed uses a simplified syntax including some support for Markdown.
- Both support cross references within the spec and references outside the spec using SpecRef [1]

Overall I am leaning towards the tool that makes it easiest for new contributors to get up to speed, and makes the editor's job easier.  Being able to iterate on the spec without a separate processing step seems like a clear win, so I propose we adopt ReSpec.

[1] https://github.com/tobie/specref

**Comment by tidoust** [comment]
@mfoltzgoogle I'm definitely fine with adopting ReSpec.

I note that the manual step to generate the HTML of a spec to publish can now be done by Echidna directly when it publishes the spec, and that ReSpec also has some (not well documented) support for Markdown [1].

There may exist a few additional differences between the tools with respect to WebIDL and cross references, for instance on ways to reference attributes from an interface from different sections in the spec.

[1] https://github.com/tobie/respec-example

**Comment by tidoust** [comment]
There may still be a few things to fix following the conversion, but the latest version of the Editor's Draft now uses ReSpec. I also updated the instructions on the Wiki.

Closing this issue as a consequence. Feel free to raise problems as needed.
