### ISSUE TITLE
Necessity of an additional state to indicate a session was resumed

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#12]
From http://webscreens.github.io/presentation-api/#open-questions:

Do we need an additional state like resumed in order to identify resumed session? It seems that this could be handled on the page level. The opener page could ask the presentation page whether it is "new" or "resumed".

**Comment by mfoltzgoogle** [comment]
The current specification provides two different mechanisms for obtaining a `PresentationSession`: a new session via `startSession()` or connection to an existing session via `joinSession()`.  Therefore the controlling page should be able to identify whether the session was started or resumed.

**Comment by avayvod** [comment]
I think this issue may have covered the case when the page connected to the existing presentation via startSession()? The presentation could communicate that to the controller page though so I don't think we need to change the spec anyway.
