### ISSUE TITLE
Section " Messaging between presentation sessions" should be updated

### ISSUE THREAD

**Issue by obeletski** [w3c/presentation-api#121]
Section [1] should be updated or dropped because
- it repeats what is already stated in [2]
- Messaging is happening between the contexts, not session [3]

1. http://w3c.github.io/presentation-api/#messaging-between-presentation-sessions
2. http://w3c.github.io/presentation-api/#sending-a-message-through-presentationsession
3. http://w3c.github.io/presentation-api/#common-idioms

**Comment by mfoltzgoogle** [comment]
@obeletski, it looks like PR #124 edited these sections to address the two issues that you mention above.  Can this issue be closed now?
