### ISSUE TITLE
Define user agent context for rendering the presentation

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#14]
The spec should specify any restrictions on the presenting browsing context when the opening browsing context is in "incognito" mode.

From [public-webscreens][1] and related threads:

The specification should define the behavior of the following Web features for the presenting page across presentation sessions. The goals are the following:

1. Ensure that the same presentation will behave correctly in the 1-UA and 2-UA cases
1. Information does not leak from presentation session to session in cases where the controlling pages may represent different authorization domains (e.g., logged-in users).

The following Web features have been discussed (and there may be others to consider):
* Cookies and local storage
* Sensor APIs (geo, orientation, etc.)
* Browser extensions
* HTTP Cache
* Shared Workers

[1]: https://lists.w3.org/Archives/Public/public-webscreens/2014Aug/0012.html

**Comment by tidoust** [comment]
See related discussion and action at Berlin F2F:
http://www.w3.org/2015/05/19-webscreens-minutes.html#item13

**Comment by anssiko** [comment]
ACTION: @mfoltzgoogle to define browsing context in terms of the upcoming spec for private browsing, perhaps using the Mozilla link as an interim reference. [recorded in http://www.w3.org/2015/05/19-webscreens-minutes.html#action14]

**Comment by anssiko** [comment]
Should also decide whether the presenting page is able to navigate to another URL.
