### ISSUE TITLE
Update PresentationAvailability.value and fire the change event in the same task

### ISSUE THREAD

**Issue by foolip** [w3c/presentation-api#143]
http://w3c.github.io/presentation-api/#interface-presentationavailability

> Queue a task to fire an event named change at availability object.

Changing the observable attribute and firing the event in separate tasks allows for the new value to be seen before the event is fired. This kind of mismatch can be tricky, for example it means that there's no guarantee that looking at the `value` attribute in the event handler there's no guarantee that one will see alternating states, for example if a device is available for just a millisecond it ought to be possible to observe `value` to be false both before and in both of the events.

Maybe just fire the event after resolving the promise?

**Comment by mfoltzgoogle** [comment]
I believe that the way that the algorithm is written, each state transition for A.value should result in a change event fired on A with the corresponding value; if A.value transitions to "false" then "true" then two events should be fired, the first with A.value == false and the second with A.value == true.

It does seem cleaner to fire the event before resolving the promise, although the caller may or may not see the first change event depending on when the event task completes vs. adding the initial event handler.

In a coming PR, I made the change above, and also consolidated the event firing task into the main algorithm to make it easier to follow.
