### ISSUE TITLE
Reconcile sessionavailable vs. sessionconnect for notifying page of session connection

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#152]
PR #146 adds a `sessionconnect` event to notify the controlling page that a presentation session is now accessible to that page.  However we previously introduced `sessionavailable` for this purpose on the presenting side.  I propose we use one event for both sides.

`sessionconnect` may not be the best name because on the controlling side, the event is fired before the session becomes connected.  Therefore I propose naming the event `sessionavailable` to denote that the session may be disconnected or connected when the event fires.

**Comment by mfoltzgoogle** [comment]
We should resolve this after #171 is closed, as we may end up with `connectionavailable` instead.

**Comment by mounirlamouri** [comment]
We just discussed this with @avayvod and we agreed that given the changes from #171 we should rename the event ```connectionavailable```.

@mfoltzgoogle if you do the changes for #171, could you apply that change too?

**Comment by mfoltzgoogle** [comment]
connectionavailable SGTM

**Comment by tidoust** [comment]
While we're renaming interfaces, would it also make sense to drop `session` from `PresentationSessionConnectEvent`, leading to `PresentationConnectEvent`?

**Comment by mounirlamouri** [comment]
I believe this should be called ```PresentationConnectionAvailableEvent``` given the recent renamings agreed upon.
