### ISSUE TITLE
Let getAvailability() resolve its promise as soon as availability has been tested

### ISSUE THREAD

**Issue by foolip** [w3c/presentation-api#161]
http://w3c.github.io/presentation-api/#dom-presentationrequest-getavailability

Reliable sources (@avayvod) tell me that the implementation in Chromium "will resolve the promise with availability false and then update the value with true as soon as the first device is found" which isn't what the spec says.

The exact details are editorial, but I would propose to resolve the promise within the definition of getAvailability() and to let the monitoring steps only fire events in case of changes.

**Comment by mounirlamouri** [comment]
The summary of the Chrome implementation is not entirely correct. If Chrome already knows of a device, it will resolve with true. IOW, it will first resolve the promise with the most recent information which would be false if it is not looking for device.

**Comment by foolip** [comment]
That actually sounds even better, because it amounts to "resolve the promise ASAP with what is known, and then fire events for changes beyond that".

**Comment by mfoltzgoogle** [comment]
@mounirlamouri's summary is correct, if we are already searching for availability we will resolve with the last known information, otherwise we will wait until availability is known.

I'm going to close this issue assuming this addresses your concern.

**Comment by foolip** [comment]
The problem is that the spec doesn't match what we all agree should be behavior, because `PresentationAvailability.value` starts out as false and only a change to that value will cause the promise to be resolved.

Can you reopen, please?

**Comment by mounirlamouri** [comment]
I will update the spec to match what we discussed here.

**Comment by foolip** [comment]
I've taken a look at the diff and I'm afraid it doesn't fully fix the problem, because while `value` is now correct, a change in value is needed to cause the promise to be resolved.

It would work to always initialize `value` to the wrong value, and at first I thought that was the fix, but it looks like it isn't. If it were up to me, I'd resolve the promise right after the changed step, and let the monitoring algorithm only care about firing the event. That should also change the input from a 3-tuple to a 2-tuple.
