### ISSUE TITLE
conflict description for uniquely identifying a presentation session

### ISSUE THREAD

**Issue by schien** [w3c/presentation-api#165]
In common idioms section, we have two different description for the unique identifier of a presentation session: 
```
A valid presentation session identifier consists of alphanumeric ASCII characters only, is at least 16 characters long, and is unique within the set of presentations.
```
and
```
The presentation session URL and presentation session identifier uniquely identify the presentation session.
```
I think we should follow the second description. However this brings up another issue on presenting side for many-to-one join session: how can a presenting page accept a incoming join request (which specify an URL and an session id) and still maintain the unique identifier within the set of presentation session.

**Comment by mfoltzgoogle** [comment]
Good points @schien.

* To accurately describe the algorithms, the set of presentations concept needs to be updated to allow multiple presentation connections to the same presentation under a single identifier.  But this should only be the case for connections obtained through `presentation.receiver`. 
* If we fix that, then for presentations with multiple connections, the first description seems more accurate.
* Also, I do think we need to define the syntax of the identifier.  Better, we should specify an algorithm for generating it.
* Issue #193 is related.

Let's close #193 and then I believe this becomes easier to define cleanly.
