### ISSUE TITLE
Rename join() to something that reflects its intended use better

### ISSUE THREAD

**Issue by avayvod** [w3c/presentation-api#170]
The suggestions comes from the discussions with Mozilla on the mailing list: https://lists.w3.org/Archives/Public/public-secondscreen/2015Aug/0017.html

I think connect() was what Mark F and both Shih-Shiang & Jonas agreed about.

**Comment by mfoltzgoogle** [comment]
Re-reading the use cases from the mailing list thread, I would now lean towards `reconnect()` as suggested by Jonas: they are all examples of a page reconnecting to an existing presentation.  

Jonas and Shih-Shiang, what do you think?

**Comment by schien** [comment]
`reconnect()` and `resume()` are both ok to me for session resumption.

**Comment by sicking** [comment]
`reconnect()` sounds great to me. Thanks!
