### ISSUE TITLE
Rename PresentationSession to PresentationController

### ISSUE THREAD

**Issue by avayvod** [w3c/presentation-api#171]
Based on https://lists.w3.org/Archives/Public/public-secondscreen/2015Aug/0027.html
Seems like renaming to PresentationController is the best way, where close() would close the presentation and an added disconnect() would detach the controller from the presentation.

**Comment by mounirlamouri** [comment]
FWIW, @sicking suggested PresentationConnection in the thread.

**Comment by avayvod** [comment]
As I understand, it depends on issue #35:
- if the api is close() to shut down presentation and disconnect() for disconnecting from it, PresentationController makes more sense (so one closes presentation via controller and disconnects the controller from it, PresentationConnection.close() would be confusing and disconnect() would sound redundant);
- if the api is close() for disconnecting and end()/stop() for actually terminating the presentation, PresentationConnection makes more sense.

Since we already have close() that means tearing down the presentation, disconnect() seems an easier path to achieve what we want, therefore PresentationController is my choice. Jonas didn't seem to have a strong opinion.

**Comment by mfoltzgoogle** [comment]
I agree with @avayvod's point of view on this.  Let's close #35 and use the result to decide this.

**Comment by sicking** [comment]
One issue is that this interface lives on both the presentation and the controller side. Something like `PresentationController` sounds to me like an object that only represents the controller side. In that regard `PresentationSession` or `PresentationConnection` is IMHO better.

I agree that it probably makes sense to make the final decision here once #35 is resolved.

**Comment by mfoltzgoogle** [comment]
@avayvod given that we have `.close()` for disconnecting and `.terminate()` for stopping presentation, the argument here lands us at PresentationConnection.  Do you agree?

**Comment by avayvod** [comment]
Yep. SGTM

**Comment by mfoltzgoogle** [comment]
SGTM
