### ISSUE TITLE
Define reconnection for cross-page navigation on presenting user agent

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#18]
Via http://lists.w3.org/Archives/Public/public-webscreens/2014Aug/0003.html

The specification does not define when the user agent rendering the presentation will be able to access the session across page navigation.

One proposal is to have the PresentationSession implement Transferable so it can be passed to and from a SharedWorker.

Another option would be for the presented page to reconnect to the session in a manner similar to the controlling page (see https://github.com/webscreens/presentation-api/issues/15).

A third option is for navigation to always terminate the presentation.  This simplifies the API and gives the session a well defined lifetime, but may be limiting to some developers.

**Comment by schien** [comment]
I would vote for the third one: terminate the presentation. For complex use case that requires navigation across pages, developer can embed iframe in the presenting page.

**Comment by mfoltzgoogle** [comment]
I agree that it's not required to support navigation in the presenting page.  We may want to permit navigation between fragment identifiers within the same document; this should be implemented as a re-rendering of the same document and does not trigger a load of a new document [1].

Are there any objections to the proposal from @schien to prohibit navigations between documents in the presenting browsing context?

[1] https://html.spec.whatwg.org/#scroll-to-fragid

**Comment by tidoust** [comment]
Re-reading this issue,

I would rather reformulate this in terms of "terminating the presentation when the receiving browsing context is unloaded", rather than "terminating the presentation when the page navigates to a different URL".

In particular, on top of fragments, it is common for apps to call `pushState` and `replaceState` to update the current URL without reloading the page.

**Comment by mfoltzgoogle** [comment]
That makes sense.  When I was looking at this earlier, I didn't find a way to allow navigation among fragment identifiers.  The flag I would set on the receiving browsing context [1] would seem to prohibit all top level navigations, even among fragment identifiers.

[1] https://www.w3.org/TR/html5/browsers.html#sandboxed-top-level-navigation-browsing-context-flag
