### ISSUE TITLE
If TV and etc have many browsers, How to select and launch the browser or web-app based on blink, gecko or webkit.

### ISSUE THREAD

**Issue by hyunjunekim** [w3c/presentation-api#189]
I think that need on the specification how to select and launch browser or web-app.
And on the blink was working to ship the presentation-API. When discovery and launch, the blink should support use of Cast and DIAL devices. 
[https://www.chromium.org/developers/design-documents/media-router]
Then has a problem using DIAL, I think we should unify the app name which is default browser or web-app to launch on the TV or other screens(presenting browsing context).

**Comment by louaybassbouss** [comment]
@hyunjunekim the Presentation API abstracts from the underlying technologies that can be used for the implementation. But in the future we may need to work on this to solve interoperability between different Presentation API implementations but for now it is out of scope in the [WG charter][1]. We already initiated a document "[Assess interoperability of Presentation API implementations][2]" to discuss interoperability. If you have feedback please submit a comment in the related issue #153. 

[1]: http://www.w3.org/2014/secondscreen/charter.html#out-of-scope 
[2]: https://github.com/w3c/presentation-api/blob/gh-pages/interoperability.md

**Comment by anssiko** [comment]
@hyunjunekim As @louaybassbouss explained, such protocol-level details are currently out of scope for this WG that is working on the API-level. I will close this issue, and encourage you to review [interoperability document][1] and submit feedback at the [related issue][2].

[1]: https://github.com/w3c/presentation-api/blob/gh-pages/interoperability.md
[2]: https://github.com/w3c/presentation-api/issues/153
