### ISSUE TITLE
Define a "set of presentations" for the receiving context?

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#193]
The "set of presentations" is defined as "the presentation sessions created by the controlling browsing contexts for the user agent'. However, the `PresentationReceiver` interface also makes use of that set, e.g. in `getSession()`: "If the set of presentations is empty, then wait until at least one element is added to the set of presentations".

However, if the UA implements both the controller and receiver interfaces, the first presentation session added to this set may not be an "incoming" presentation session. It could be a session created through a call to `start()` instead.

The prose could perhaps be adjusted to distinguish entries in that set based on the URL (null for incoming presentations, set for those created). However, it seems easier to define a separate "set of presentations" for the receiving context, which could perhaps be named "set of incoming presentations".

What do you think?

**Comment by mfoltzgoogle** [comment]
We need to distinguish the following three sets, as they are distinct:

- The set of presentation sessions created for a controlling browsing context via start/reconnect
- The set of presentation browsing contexts acting as a presentation receivers
- The set of presentation sessions provided to the presentation receiver

**Comment by mfoltzgoogle** [comment]
Also from PR #221:

> The text about "PresentationReceiver object" should probably move
> to the section about the Presentation interface. This section is
> about the interface, not its instance (the object).

> Furthermore, we probably need a better way to explain how
> PresentationConnectionList is initialized -- how the set of
> presentations is populated.
