### ISSUE TITLE
Message sending in Example 5 happens too early

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#198]
The code in example 5 apparently assumes that it may issue a `send` command right away:
http://w3c.github.io/presentation-api/#monitor-session-s-state-and-exchange-data-example

However, I don't see what guarantees that this won't thrown an error in the spec. The algorithm to etablish a presentation connection runs in the background in particular, so I would expect the returned PresentationSession to be in "disconnected" state to start with:
http://w3c.github.io/presentation-api/#dfn-establish-a-presentation-connection

And the algorithm to send a message throws an exception if the state is not "connected":
http://w3c.github.io/presentation-api/#dfn-send-a-message-through-a-presentationsession-s

Happy to prepare a PR if I'm right.

**Comment by louaybassbouss** [comment]
Hi @tidoust yes we should check the session's state before sending the message or we can put the send call in a `try-catch` block.

**Comment by anssiko** [comment]
Reopened per F2F discussion.

**Comment by tidoust** [comment]
See relevant discussion at TPAC F2F:
http://www.w3.org/2015/10/28-webscreens-minutes.html#item04

**ACTION**: Mark and Louay to rework example 5 and refine spec prose to clarify the initial connection state when the connection is created

**Comment by mfoltzgoogle** [comment]
PR #227 modifies the example code to send messages only on a "connected" presentation connection.
It also creates new connections in a "connecting" state.
