### ISSUE TITLE
Add definition for "presentation" to Common idioms

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#209]
Noting that we're missing the formal definition for "presentation". It is implicitly defined in the introduction as follows: "[...] another page that represents the presentation shown in the presentation display"

Given this is pretty central concept, we should define it in Common idioms. There's some room for confusions since we have both [an interface][1] as well as [an attribute][2] with the same name.

[1]: http://w3c.github.io/presentation-api/#interface-presentation
[2]: https://w3c.github.io/presentation-api/#idl-def-navigator-presentation

**Comment by mfoltzgoogle** [comment]
It's defined in common idioms as follows:

> The receiving browsing context (or *presentation* for short) is the browsing context responsible for
> rendering to a presentation display. A receiving browsing context can reside in the same user agent as > the controlling browsing context or a different one.

**Comment by anssiko** [comment]
Thanks, I missed it since it was styled with &lt;code&gt;.
