### ISSUE TITLE
Add a "starting" state to PresentationConnection

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#214]
When calling PresentationRequest.start(), it may take some time for the presentation to be fully loaded and ready for connection on the presentation screen.

In the meantime, the controlling page is unaware of the initialization progress of the presentation, since we only resolve the Promise with a connected PresentationConnection.  Activities (i.e., media playback) will continue in the meantime, while the user has already indicated they want the content to be presented remotely, which creates a jarring user experience.   If the controlling page were aware that presentation was starting, it could pause the media and update the UI to show the user what was happening.

@avayvod has proposed adding a starting state to the PresentationConnection, with a new start algorithm that would roughly go as follows:

1. If the user selects a screen, then resolve the Promise right away with a "starting" PresentationConnection. 
2. If the user cancels presentation, reject the Promise.
3. Once the receiving context is fully loaded, transition the PresentationConnection to connected.
4. If there is an error loading the receiving context then transition to disconnected (or perhaps a new error state).

Messaging would be allowed during the "starting" state in case the presentation wants to convey metadata about the chosen screen, or show some progress information.

**Comment by mounirlamouri** [comment]
This is somethnig we wanted to add to the Remote Playback API too. I think it would be great to have this state. Though, we might want to call it `connecting` for consistency with `connected`?

**Comment by avayvod** [comment]
Since sending and receiving messages to/from a "connecting" connection might sound confusing, and w/o this extra functionality "connecting" state doesn't add much, maybe there're other ways we could workaround passing the metadata etc?
1. Return the PresentationConnection in a "disconnected" state when the user picks a screen, but with some custom dictionary "screen" field that would contain the available metadata? Once the connection is established, the PresentationConnection changes to a "connected" state.
2. Return the PresentationConnection in a "connected" state when the user picks a screen to allow messaging and handle the messages requiring a working connection by queueing them until the underlying connection to the screen is established.

**Comment by tidoust** [comment]
Hi @avayvod,

> Since sending and receiving messages to/from a "connecting" connection might sound confusing, and w/o this extra functionality "connecting" state doesn't add much, maybe there're other ways we could workaround passing the metadata etc?

While there may be better ways to expose messaging channels, consistency across similar specs seems like a good idea.

Typically, both WebSockets and WebRTC data channels have `connecting`, `open`, `closing` and `closed` ready states:
https://html.spec.whatwg.org/multipage/comms.html#dom-websocket-readystate
http://w3c.github.io/webrtc-pc/#idl-def-RTCDataChannelState

They also both throw an error when a message is sent while the ready state is `connecting`:
https://html.spec.whatwg.org/multipage/comms.html#dom-websocket-send
http://w3c.github.io/webrtc-pc/#dom-datachannel-send

I don't think there is any notion of message buffering in these specs either: `open` means the message can, in theory at least, be delivered immediately.

The `connecting` proposal would align the spec nicely with the two other specs. The alternatives you suggest would create a different scheme which, while better in some cases, may also confuse developers used to dealing with WebSocket channels. Do we need to solve a specific case that WebSockets and WebRTC data channels do not have?

**Comment by avayvod** [comment]
Ok, I agree that having a "connecting" state is beneficial for consistency and convenience.
I don't think we should add any exceptions for messaging in non "connected" state too. Implementations should be able to work around the passing screen metadata problem (e.g. pass the info when the connection is in the "connected" state) and wait until it's in the spec somehow.

**Comment by mfoltzgoogle** [comment]
Okay, it sounds like there is consensus on retaining the "connecting" state in PR #227.

**Comment by mfoltzgoogle** [comment]
Merged PR #227 which adds a "connecting" state to the API.  New presentation connections to the controller are provided to the page in this state and later transition to "connected."

Note that connections are provided to the receiving context in an already-"connected" state.
