### ISSUE TITLE
Add a PresentationConnection.disconnected state for accidental disconnections

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#217]
Some interactive applications (e.g., games) may want to pause when the controller has accidentally disconnected.  Right now this can only be detected indirectly when a call to `connection.send()` fails - the connection will transition to `closed` and fire an error event.  To detect this quickly, the application would likely need some kind of heartbeat mechanism - depending on the channel implementation.

This issue tracks whether we want to add back a `disconnected` state so the application can more directly be notified when this happens.  This implies the implementation would need to come up with its own heartbeat mechanism under the covers.

@sicking, feel free to add more context.

**Comment by mounirlamouri** [comment]
I'm slightly confused by this, how is the UC not fulfilled with:
```js
var connection = getTheConnection();
connection.onstatechange = function() {
  if (connection.state != 'connected') {
    handleDisconnect();
  }
};
```

**Comment by mfoltzgoogle** [comment]
I believe the use case is to distinguish intentional disconnection from accidental disconnection.  In the former case you would exit the game and ask for new players.  In the latter case you would pause the game, prompt the user to reconnect their controlling device to the display, and resume play when they had done so (or eventually time out).

**Comment by mounirlamouri** [comment]
Wouldn't that be better to create a `PresentationConnectionStateChangeEvent` that would be use when firing a `statechange` event instead of firing a `simple event`? We could add some property there. For example `userInitiated`. It sounds cleaner than creating a new concept (`disconnected`) that wouldn't really mean what it says -- If I understand correctly, `disconnected` isn't really that the connection is disconnected but that it was `closed` without user intervention.

**Comment by mfoltzgoogle** [comment]
Since the only state change that would need further explanation is the one that transitions from connected to closed, what about firing a separate `CloseEvent` with a result code, similar to WebSockets? [1]  We could use this to also convey the last message sent if the socket closed with a write error, which would resolve #149 and no longer require a separate `error` event.

Specific proposal:

```
partial interface PresentationConnection : EventTarget {
    attribute EventHandler                onclosed;
}

enum PresentationConnectionCloseReason {
    "user_requested",   // User navigated, closed tab
    "page_requested",  // Page called .close()
    "send_error",          // Failed to send a message
    "read_error"           // Unable to read further messages
}

[Constructor(DOMString type, PresentationConnectionCloseEventInit eventInitDict)]
interface PresentationConnectionCloseEvent : Event {
    [SameObject]
    readonly attribute PresentationConnectionCloseReason closeReason;
    // Includes the message that failed to be sent if closeReason == "send_error"
    readonly attribute DOMString errorMessage;
};

dictionary PresentationConnectionAvailableEventInit : EventInit {
  PresentationConnectionCloseReason closeReason;
  DOMString errorMessage;
};
```

[1] https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent

**Comment by anssiko** [comment]
Seems good. Some comments:

* Perhaps for consistency the attribute should be simply `reason`.
* TAG has some casing rules for enumeration values: http://w3ctag.github.io/design-principles/#casing-rules I think lowercase, concatenated would be fine too, since I'm not seeing lowercase, dash-delimited much in use actually.

**Comment by mfoltzgoogle** [comment]
PR #227 landed a modified version of this proposal with close reasons of "error" (all accidental/error related cases), "closed" (all user or page initiated cases), and "wentAway" (navigations).

I believe it addresses the naming issues in https://github.com/w3c/presentation-api/issues/217#issuecomment-161958769 as well.

**Comment by mfoltzgoogle** [comment]
Although "wentAway" should perhaps be "wentaway."  Any opinion @annsiko?

**Comment by anssiko** [comment]
@mfoltzgoogle Lowercase is what the rest of the platform uses for enums, also recommended by the [WebIDL spec][1]:

>It is strongly suggested that enumeration values be all lowercase, and that multiple words be separated using dashes or not be separated at all [...]

Submitted a PR #237 with a fix.

[1]: http://heycam.github.io/webidl/#idl-enums
