### ISSUE TITLE
Implementation guideline: users should have a way to know which origin is being presented at any time 

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#223]
The issue was raised during last Privacy INterest Group (PING) call, that @mfoltzgoogle and myself attended on behalf of the Second Screen WG.

The Presentation API should provide guidance to implementers around the need to ensure that the user can tell which origin is being presented at any time (when the request to present is made, as well as while the presentation is on-going).

See draft minutes of the PING call:
http://www.w3.org/2015/12/03-privacy-minutes.html#item02

**Comment by mfoltzgoogle** [comment]
Request for clarification: Is the suggestion to show the origin that is requesting presentation (i.e. from a controlling browsing context) or the origin being presented (i.e. in a receiving browsing context).

**Comment by tidoust** [comment]
My recollection of the discussion we had with PING is that the focus was from a controlling browsing context perspective, and that the goal was to ensure that the user has a way to tell which origin is being presented from the chrome of the controlling user agent.

I realize that, in the generic case, the controlling user agent may not be able to guarantee that the origin displayed in its chrome is the one actually presented by the receiving user agent: it needs to assume that the receiving user agent is behaving as requested.

Also, the discussion on nested contexts also points out the need to show the requesting origin in the picker UI: https://github.com/w3c/presentation-api/issues/79#issuecomment-156304038

I would not add specific guidelines from a receiving browsing context perspective. I would rather treat the receiving user agent as a "regular" user agent rendering Web content. The final conclusion of #99 "Define behavior of Window and Fullscreen APIs in the presentation browsing context" could perhaps require a different approach.

**Comment by mfoltzgoogle** [comment]
Thanks, that was my understanding as well.  I don't plan to propose any guidelines for the receiving user agent, at this point, although as you say in the 2-UA case the controlling UA would have to assume it's behaving as expected.

Instead, I will propose some guidelines for the controlling user agent to show the user what origin is being requested for presentation.

**Comment by mfoltzgoogle** [comment]
Actually the PR does talk about the requirements for the receiving user agent, but not the receiving browsing context.  (I think that reflects the idea of https://github.com/w3c/presentation-api/issues/223#issuecomment-177902959).

**Comment by tidoust** [comment]
The PR looks good but only covers the case when the user is asked for permission. It does not suggest that the controlling user agent should provide users with a way to tell which origin is being presented at any time after that, as initially suggested by PING. Or is that on purpose (e.g. because it may not be able to guarantee that the information is correct as raised above)?

**Comment by mfoltzgoogle** [comment]
I think resolving #18 as you suggested will take care of this, although we should probably say something about using the origin loaded in the receiving browsing context after redirects are resolved.

**Comment by mfoltzgoogle** [comment]
Closing this issue, assuming that we resolve #18 to ensure that the receiving browsing context cannot navigate across origins.
