### ISSUE TITLE
Presentation API IDL Tests for Presentation Interface

### ISSUE THREAD

**Issue by louaybassbouss** [w3c/presentation-api#230]
The Presentation API specifies interfaces for controlling and receiving user agents in the same spec. The [Presentation Interface][1] is one of the common interfaces used in both classes of user agents. In controlling UA only the `defaultRequest` attribute is relevant and for receiving UA only the `receiver` attribute. If one of these attributes is `undefined` (e.g. `defaultRequest` is not defined in receiving user agent or `receiver` is not defined in controlling user agent), the IDLharness will fail. I see 3 options to solve the problem:
1. Modify the Presentation Interface in the idlharness by remove the defaultRequest attribute in the idlharness of receiving UA and receiver attribute in the idlharness of controlling UA.
2. Implementors set `defaultRequest` to `null` in receiving UA and `receiver` to `null` in controlling UA (need to make this also clear in the spec). 
3. Define two different interfaces instead of one common Presentation Interface. 
 
I prefer option 2. What do you think?

[1]: http://w3c.github.io/presentation-api/#interface-presentation

**Comment by mfoltzgoogle** [comment]
Also see Issue #205 where I raise the issue of how to treat `defaultRequest` and `receiver` in UAs that conform to one class but not the other. 

Personally I would prefer leaving the attributes undefined in user agents that don't implement the corresponding interfaces or functionality.  Literally there is no reason to have the attribute at all and that is consistent with other cases where the user agent does not implement a web platform feature, i.e. as a developer I would expect Navigator.foo to be undefined if foo is not implemented.

I guess this is option #1 above?

For IDL harness testing, maybe we can tag parts of the IDL to be present in the receiving or controlling UA, and extract two different IDLs.  Each conformance class should have its own IDL test anyway, right?

**Comment by louaybassbouss** [comment]
@mfoltzgoogle I just replied to your original issue #205.  Regarding your question: exactly each conformance class have its own IDL test. If we tag in the spec the parts of the IDL to be present in the receiving or controlling UA, we can then extract the IDL for each conformance class automatically.  For now I extract the complete IDL using the following function and then split the IDL for each conformance class manually. maybe we can define two additional classes `idl-controlling-ua` and `idl-receiving-ua` so that we can extract each of them separately e.g. by using `document.getElementsByClassName("idl-controlling-ua")` or `document.getElementsByClassName("idl-receiving-ua")` : 

```javascript
(function(){
  var s = "";
  [].forEach.call(document.getElementsByClassName("idl"), function(idl) {
    if (!idl.classList.contains("extract"))
      s += idl.textContent + "\n\n";
  });
  document.body.innerHTML = '<pre></pre>';
  document.body.firstChild.textContent = s;
  })();
``` 

You can close this task.

**Comment by mfoltzgoogle** [comment]
Thanks @louaybassbouss.

**Comment by anssiko** [comment]
To make programmatic IDL extraction possible, you could split IDL blocks using `partial interface` as follows:

```
<pre class="idl idl-controlling-ua">
partial interface Presentation {
  attribute PresentationRequest? defaultRequest;
};
</pre>
<pre class="idl idl-receiving-ua">
partial interface Presentation {
  [SameObject] readonly attribute PresentationReceiver? receiver;
};
</pre>
```

The spec is currently worded as per option 1, i.e. the attributes are null in the other context:

>In a controlling user agent, the `defaultRequest` attribute must return the default presentation request if any, null otherwise.

>In a receiving user agent, the `receiver` attribute must return the `PresentationReceiver` instance associated with the receiving browsing context and created by the receiving user agent when the receiving browsing context is created. In any other browsing context, it must return null.

To specify this as per option 2, i.e. the attributes do not exist in the other context, we would probably need to use the [\[Exposed\] extended attribute][1], and define another global object e.g. `PresentationWindow` to be used in the receiving browsing context, and then add `[Exposed=PresentationWindow]` in front of the latter `partial interface Presentation` IDL block. There may be other caveats.

All - which way would be preferred?

[1]: https://heycam.github.io/webidl/#Exposed

**Comment by anssiko** [comment]
It appears https://github.com/w3c/presentation-api/pull/261 already clarified the handling of attributes (addressing https://github.com/w3c/presentation-api/issues/205), so we can close this issue (again).

@mfoltzgoogle @louaybassbouss you may still want to consider splitting the relevant IDL block into two `partial interface` blocks to ease programmatic IDL extraction. That is an editorial change, and can be handled after we first publish.

**Comment by tidoust** [comment]
@anssiko Web IDL is not entirely clear about that but I think that there would need to be a concrete `interface` defined that the `partial interface` blocks would extend. In our case, that would mean adding the following empty interface somewhere:

```html
<pre class="idl">
  interface Presentation {};
</pre>
```

**Comment by anssiko** [comment]
@tidoust that is correct, we need such an empty concrete interface since there are no other interface members. Thanks for clarification.
