### ISSUE TITLE
Describe the use cases for terminate vs close

### ISSUE THREAD

**Issue by birtles** [w3c/presentation-api#242]
Not sure if this is the most appropriate place for feedback, but as a newcomer to the spec I'm having trouble understanding the use cases behind terminating vs closing. It seems that closing allows you to reconnect whereas terminate does not but I'm still puzzled as to what use cases they represent.

**Comment by mfoltzgoogle** [comment]
We should ensure the use cases/reqs document [1] and examples [2] cover both of these use cases, and it's clear from reading the examples which use cases are demonstrated.  I'm pretty sure they do, but some clarifications are possible.

[1] https://github.com/w3c/presentation-api/blob/gh-pages/uc-req.md
[2] http://w3c.github.io/presentation-api/#examples

**Comment by mfoltzgoogle** [comment]
@birtles Sorry it took a while to get back to this!  Please take a look at PR #307 and see if that clarifies things for you.  Thanks.

**Comment by birtles** [comment]
Thanks, looks good.
