### ISSUE TITLE
getAvailability procedure is not specified

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#246]
The spec does not explain what happens when the `getAvailability` method is called. In particular, the procedure needs to describe when the `Promise` is resolved.

**Comment by tidoust** [comment]
@mfoltzgoogle I think you dropped the procedure by mistake when re-ordering sections in December. PR #247 should fix the issue.

**Comment by mfoltzgoogle** [comment]
Should be closed by #247.
