### ISSUE TITLE
When is the first presentation connection created in the receiving browsing context?

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#254]
The spec does not say anything about the creation of the first presentation connection in the set of presentations on the receiving side.

When the receiving browsing context is created, the `PresentationReceiver` singleton is created as well. Should the receiving user agent also create the first `PresentationConnection` instance at the same time? Also, what should its presentation connection state be?

**Comment by mfoltzgoogle** [comment]
Closed by PR #277.
