### ISSUE TITLE
Should `reconnect` fire a `connectionavailable` event when it returns an existing presentation connection?

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#259]
Right now, the `reconnect` procedure always fires a `connectionavailable` event, even when it returns a `PresentationConnection` object created by the current browsing context.

Without having given it much thoughts, I would rather assume that a given `PresentationConnection` instance would only trigger one `connectionavailable` event. That seems to match the description of the `PresentationConnectionAvailableEvent` interface, which suggests that the event only fires "when a connection associated with the [PresentationRequest] object is **created**".

Fake code example:

```js
var connection = null;
var request = new PresentationRequest(url);
request.onconnectionavailable = function (evt) {
  connection = evt.connection;
});

[...]
// Call to start will trigger a "connectionavailable" event
request.start();

[...]
// Call to reconnect will return the same connection instance,
// should it really trigger another "connectionavailable" event?
request.reconnect(connection.id);
```

**Comment by mfoltzgoogle** [comment]
I agree your interpretation is more consistent with the event definition.  Feel free to submit a PR to remove step 6-3 from the reconnect algorithm.
