### ISSUE TITLE
Annotate IDL blocks with idl-controlling-ua and/or idl-receiving-ua classes

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#268]
Via @louaybassbouss:

Add for all IDLs the class `idl-controlling-ua` or `idl-receiving-ua` to make extraction (programatically) of IDLs for only controlling UA or receiving UA easier. If an IDL is required for both conformance classes (e.g. `PresentationConnection`), we can assign the two classes to the IDL at same time.

**Comment by louaybassbouss** [comment]
Thx @anssiko LGTM
