### ISSUE TITLE
Define a Multiplayer Gaming Use Case

### ISSUE THREAD

**Issue by louaybassbouss** [w3c/presentation-api#27]
**Poker**

> Bob enters an online poker site on his smartphone to play poker with friends. He selects the option "`create new game`" to start a game session for two players. The poker site detects that there is display  available and asks Bob to extend the game UI by keeping his personal cards and control UI on the smartphone and displaying the poker table on the large display. Bob confirms and waits for other players to join. Alice is visiting Bob and decides to join the game. She opens the same poker site in the browser on her smartphone and selects the option "`join game`". The browser shows a dialog with a list of running poker sessions. She selects the session started by Bob and joins the game. The game starts immediately after two players are joined. Now Alice and Bob can see their personal cards on their smartphones and the large screen displays the poker table with shared cards, current bets, and remaining money of each player.

**Poker Player View**

![player1](https://cloud.githubusercontent.com/assets/1138409/5085157/64253b5e-6f0f-11e4-964a-fe9bd7e4abba.png)

**Poker Table Screen**

![table1](https://cloud.githubusercontent.com/assets/1138409/5085191/a5267e42-6f0f-11e4-883c-07bd6bf68065.jpg)

**Comment by louaybassbouss** [comment]
I will assign this issue to myself

**Comment by mfoltzgoogle** [comment]
I think this can be closed now based on PR #98, as the use cases document does include the poker example from this issue.
