### ISSUE TITLE
Use NotAllowedError for permission denied instead of AbortError

### ISSUE THREAD

**Issue by tobie** [w3c/presentation-api#271]
When the user denies permission in step 10 of [6.3.2 Starting a presentation](https://w3c.github.io/presentation-api/#starting-a-presentation), the promises is rejected with an `AbortError`.

It seems a more appropriate error would be the [`NotAllowedError`](http://heycam.github.io/webidl/#notallowederror); unless, of course, `PermissionDeniedError` [becomes a thing](https://github.com/heycam/webidl/issues/95).

**Comment by mounirlamouri** [comment]
Using `NotAllowedError` here sgtm. I sent a PR: #272.

**Comment by tidoust** [comment]
PR was merged, closing this issue accordingly.
