### ISSUE TITLE
Specify the algorithm for generating a presentation identifier

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#279]
This idea has been raised a couple of times, including in:

* #165 conflict description for uniquely identifying a presentation session, see https://github.com/w3c/presentation-api/issues/165#issuecomment-147452520
* #253 Have the receiving browsing context generate the presentation identifier?

The presentation identifier needs to be unique across possible controlling and receiving browsing contexts that belong to the same local user environment. The best way to almost-guarantee the unicity of the presentation identifier is to specify the algorithm that the controlling user agent must follow to create an identifier.

The usual reference for generating Universally Unique IDentifiers (UUID) seems to be RFC4122:
https://tools.ietf.org/html/rfc4122

This may be overkill in our context. Nothing comes to mind but there may be other examples of specs that define a lightweight version of such an algorithm.

**Comment by mfoltzgoogle** [comment]
I'll follow the example of the MediaStream.id specification, which references specific sections of RFC 4122 [1].

[1 ]http://w3c.github.io/mediacapture-main/#attributes

**Comment by mfoltzgoogle** [comment]
PR #284 posted to address this issue.

**Comment by mfoltzgoogle** [comment]
Closing with the PR that specifies the ID generation algorithm.
