### ISSUE TITLE
PresentationReceiver.connectionList doesn't return the same object all the time

### ISSUE THREAD

**Issue by schien** [w3c/presentation-api#281]
In current WebIDL definition `connectionList` is marked with `[SameObject]` extended attribute [1].
```
interface PresentationReceiver {
    [SameObject]
    readonly attribute Promise<PresentationConnectionList> connectionList;
};
```
However in the algorithm it will create a new Promise object once the previous one is settled, which conflict to the `[SameObject]` contract.

s/unsettled Promise/Promise in step 1 should make the algorithm follow the WebIDL definition.

[1] https://w3c.github.io/presentation-api/#interface-presentationreceiver

**Comment by mfoltzgoogle** [comment]
This should also be addressed by PR #277.
