### ISSUE TITLE
define the detailed behavior of disable Presentation API in sandbox

### ISSUE THREAD

**Issue by schien** [w3c/presentation-api#288]
In current spec it only says:
```
Presentation is disabled in a browsing context when the document object's active sandboxing flag set does not have the sandboxed presentation browsing context flag set. 
```

There are two entry points of Presentation API for controller.
1. navigator.presentation: we can return `null` if Presentation API is disabled in sandbox.
2. window.PresentationRequest: we can either throw a `InvalidAccessError` while constructing PresentationRequest or hind PresentationRequest from window object.

**Comment by mfoltzgoogle** [comment]
@schien, can you please review the spec after I just merged PR #292 by @mounirlamouri and let me know if it addresses your concerns.

**Comment by schien** [comment]
I'm ok with always return a valid `Presentation` object and throw `SecurityError` while accessing it in sandbox.

**Comment by mfoltzgoogle** [comment]
Thanks @schien.  Closing now.
