### ISSUE TITLE
[meta] Publish a new Working Draft before the F2F - review the latest ED by 9 May

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#289]
The latest formal publication of the Presentation API is the [W3C Working Draft 11 February 2016][1].

Since then, we've resolved all the issue that were identified as ones that can be address before the F2F (see #276). I suggest we publish a new WD before the F2F, since these changes are considered significant, and it is good to have a fresher spec on TR in general.

@tidoust I assume no process issues in publishing a WD now, even if the previous WD was blessed as the "wide review" WD? The 2015 process seem to give freedom to publish revised WDs even after the wide review WD shipped.

@mfoltzgoogle Please publish a new WD using the process defined in the [Work Mode][2] after merging the PR in flight #287 (unless it requires further discussion). I'd suggest we publish earliest on 10 May to give the group time to take a look at the latest [ED spec][3] used as the basis before we publish.

(After we ship this WD update, the next publication step after the F2F would likely be to advance the spec to CR. We're trending toward mid-2016 publication for the CR. Keep up the good work!)

[1]: https://www.w3.org/TR/2016/WD-presentation-api-20160211/
[2]: https://www.w3.org/wiki/Second_Screen/Work_Mode#Publication_as_Working_Draft
[3]: https://w3c.github.io/presentation-api/

**Comment by tidoust** [comment]
@anssiko I confirm that there are no process issues. The concept of "wide review WD" does not even exist as such in the process. I created PR #291 to refresh the Status of This Document section for the upcoming publication and in particular summarize the changes made since February.

**Comment by anssiko** [comment]
Hearing no concerns and #291 landed, we're good to publish a new Working Draft.

@mfoltzgoogle please proceed with the WD publication.

**Comment by mfoltzgoogle** [comment]
A new Working Draft has been published, dated 10 May 2016.

https://www.w3.org/TR/2016/WD-presentation-api-20160510/

**Comment by anssiko** [comment]
Congrats and thanks everyone who helped make the spec ready for publication.

The Presentation API publication history https://www.w3.org/standards/history/presentation-api
shows how each new WD has improved the spec. The next publication milestone will be Candidate Recommendation, tracked in #276.
