### ISSUE TITLE
Move sandbox flag to HTML spec

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/presentation-api#299]
What the spec does is monkey patching the HTML spec which isn't great. They take pull request nowadays so we should probably send one.

**Comment by anssiko** [comment]
ACTION @mounir to craft a PR to upstream this feature to HTML.
ACTION @tidoust to update the SoTD section to mention the upcoming move.

**Comment by mounirlamouri** [comment]
@tidoust this is now part of the HTML spec but I realise that Presentation API only uses the W3C-HTML spec so I can't yet update the spec. Can you ping some W3C folks to cherry-pick the change? :)
