### ISSUE TITLE
Add presentation request URL fallback mechanism

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#311]
[Discussed at the F2F, carving out into a separate issue.]

**PROPOSED RESOLUTION**: Add a fallback mechanism by adding a new constructor on `PresentationRequest` that takes an Array of DOMString, and by exposing the presented URL in an "url" attribute on `PresentationConnection`, pending feedback from implementers that this is doable.

For the full issue description and discussion, please refer the [F2F Day 2 minutes][1].

[1]: https://www.w3.org/2016/05/25-webscreens-minutes.html#item03

**Comment by anssiko** [comment]
@mfoltzgoogle Did you receive feedback from your folks on the feasibility? This remains the only, and pretty essential, unresolved issue blocking our CR release.

**Comment by mfoltzgoogle** [comment]
I did get feedback on this issue.  It will take 2-3 weeks of effort but should not significantly derail the timeline for us to get to CR.

As far as the PR to implement the resolution, @mounirlamouri offered to draft one, but he has been pulled into other urgent work.  After addressing other issues in this repo, I can take this on.

**Comment by anssiko** [comment]
Fixed with #316.
