### ISSUE TITLE
Clear service worker's persistent storages in a receiving browsing context

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#318]
[This issue is spun off from #275.]

Need to specify how the service worker’s [persistent storages][1] are cleared in the receiving browsing context when [creating and closing a receiving browsing context][2] in accordance with the [User Data Controls in Web Browsers][3] guidelines.

[1]: https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#privacy
[2]: https://w3c.github.io/presentation-api/#creating-a-receiving-browsing-context
[3]: https://gist.github.com/mnot/96440a5ca74fcf328d23

**Comment by tomoyukilabs** [comment]
I'd like to show a rough proposal like below:

When creating a receiving browsing context,

* create a new empty [list of registered service worker registrations](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#service-worker-registration-lifetime) for the receiving browsing context. (This corresponds to "scope to registration map" and "script resource map".)
* create a new empty [caches](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#cache-objects) for the receiving context. (This corresponds to "request to response map" and "name to cache map".)

When the receiving browsing context is alive, (for the purpose of ensuring interoperable behavior for 1-UA and 2-UA cases)

* [window and worker clients](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#service-worker-client-concept) in the receiving browsing context must not be exposed to service workers (via [`self.clients`](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#clients)) registered in the other browsing context.
* window and worker clients in the other browsing context than receiving browsing context must not be exposed to service workers registered in the receiving browsing context.

When closing the receiving browsing context,

* service workers registered in the receiving browsing context must be unregistered. (Note: Do the service workers have to be terminated immediately? [Service Workers spec](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#navigator-service-worker-unregister) says service workers remain effective until they are unloaded.)
* any associated browsing state, including a list of registered service worker registrations and caches, must be discarded.

Is there any other thing to be specified?

**Comment by anssiko** [comment]
Thanks @tomoyukilabs! Could you perhaps craft a PR to help integrate this to the spec? We can iterate it further using PR comments as needed ([instructions in the wiki][1]).

Alternatively, @mfoltzgoogle as the editor can probably help with the PR too.

[1]: https://www.w3.org/wiki/Second_Screen/Work_Mode#Direct_Spec_Contributions

**Comment by tomoyukilabs** [comment]
@anssiko Thank you so much for instructions! I will prepare a PR.
