### ISSUE TITLE
"SHOULD act as if " is unclear

### ISSUE THREAD

**Issue by smaug----** [w3c/presentation-api#323]
"If the the document object's active sandboxing flag set has the sandboxed presentation browsing context flag set, the controlling user agent SHOULD act as if the default request is not set for that browsing context." 
In which way it should act? Does it mean it should internally not use defaultRequest for anything, 
or does it also mean that defaultRequest should keep returning null or what?

**Comment by mounirlamouri** [comment]
The gist is that the property should keep working (not sure if it's okay to leak the sandbox status) but the UA shouldn't use the information for things like chrome button to "present" tab.
