### ISSUE TITLE
PresentationRequest constructor uses entry settings object, but it probably shouldn't 

### ISSUE THREAD

**Issue by smaug----** [w3c/presentation-api#336]
See https://html.spec.whatwg.org/multipage/webappapis.html#realms-settings-objects-global-objects
"The incumbent and entry concepts should not be used by new specifications, as they are excessively complicated and unintuitive to work with."

**Comment by tidoust** [comment]
See [discussion at TPAC](http://www.w3.org/2016/09/22-webscreens-minutes#ins10)

**PROPOSED RESOLUTION:** For #336, examine how other specs have been updated to use the settings object and update our spec to match.

**Comment by domenic** [comment]
You want current settings object here. Quoting from the link in the OP,

> In general, web platform specifications should use the relevant concept, applied to the object being operated on (usually the this value of the current method). This mismatches the JavaScript specification, where current is generally used as the default (e.g. in determining the JavaScript realm whose Array constructor should be used to construct the result in Array.prototype.map). But this inconsistency is so embedded in the platform that we have to accept it going forward.
>
> **Note that in constructors, where there is no this value yet, the current concept is the appropriate default.**

**Comment by mfoltzgoogle** [comment]
OK.  What is the relationship between the _current settings object_ and the _environment settings object_ for a given function invocation in a document?  The settings object properties needed to implement  the algorithms (API base URL and https state) are defined on the latter, not the former.

**Comment by domenic** [comment]
"the environment settings object for a given function invocation in a document?"

This concept does not exist.
