### ISSUE TITLE
PresentationConnectionList is not required for receiving user agents

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#337]
The receiving user agent conformance class (section 3.1) does not require implementation of PresentationConnectionList.  It seems like a simple typo.

**Comment by tidoust** [comment]
See [discussion at TPAC](http://www.w3.org/2016/09/22-webscreens-minutes#ins09)

**PROPOSED RESOLUTION:** For #337, add PresentationConnectionList to the list of interfaces to be supported by receiving user agents.
