### ISSUE TITLE
Can the same browsing context act as a controller and receiver?

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#338]
We may have discussed this tangentially in a previous issue.  The spec is ambiguous as to whether a receiving browsing context can also be a controlling browsing context in a user agent that implements both conformance classes.  It doesn't prohibit it, but there might be some implementation challenges given the restrictions the spec places on a receiving browsing context (don't show modal UI, etc.)

Here are some possible use cases:
- Starting a multi-display presentation with a "parent" presentation connected to the controller and "child" presentations connected to the parent.
- Having a presentation be able to launch a controller.  For example a smart TV could be configured to start a remote control application on a nearby device it had discovered.   Related to Issue #32.

Filing this issue to nominate for the agenda at TPAC.

**Comment by tidoust** [comment]
For reference, see [related discussion at TPAC](http://www.w3.org/2016/09/22-webscreens-minutes#ins16)

**Comment by jimmywarting** [comment]
I have two android devices, one is connected to good speakers. atm I would like to use one of them as an audio cast receiver/player. And use the second one as a remote controller. would be cool if you somehow could register as a receiver.

**Comment by mfoltzgoogle** [comment]
Hi @jimmywarting, if they are two distinct devices, then you have a few options.  For example the audio receiver device could be a target for the Remote Playback API or the Presentation API from Chrome.

Right now the only way I know to do that on Android is to use an Android TV device, which implements the Chromecast protocols natively, but there may be other open source or third party software available that would work too.

**Comment by mfoltzgoogle** [comment]
Back to the original issue, which is about a presentation receiver page being allowed to initiate a presentation.  From a spec point of view, I don't see any particular restriction on it; it's really a matter of the user interface to give the presentation the permission o launch another presentation.

This could happen (for example) you use the controller API to initiate a presentation on a secondary monitor, then call `PresentationRequest.start()` from the presentation page, where you could use your mouse to interact with the dialog.   This doesn't work in Chrome right now (the dialog doesn't show up) but that's an implementation limitation.

I think this can be addressed with a non-normative note saying something like, "It is possible for a presentation to start another presentation, but not all browsers may choose to implement this."
