### ISSUE TITLE
setConnection in example 5.5 may put UI in an inconsistent state

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#339]
`setConnection()` calls `close()` on an existing connection before adding an `onconnect` handler to the new connection.  If the close event on the old connection fires after the connect event on the new connection, `reset()` will null out the new connection and disable the stop and disconnect buttons.

**Comment by tidoust** [comment]
See [discussion at TPAC](http://www.w3.org/2016/09/22-webscreens-minutes#ins08)

**ACTION:** @kenchris to review and fix the example in 5.5

**Comment by kenchris** [comment]
https://github.com/w3c/presentation-api/pull/358

**Comment by mfoltzgoogle** [comment]
Closing with the fixes in the PR.
