### ISSUE TITLE
navigator.presentation is marked optional in WebIDL

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#341]
In section 6.2, the presentation attribute is marked optional.  However the text says that it is mandatory for all conforming user agents to return an instance of Presentation.   I think this is just an IDL bug.

**Comment by tidoust** [comment]
See [discussion at TPAC](http://www.w3.org/2016/09/22-webscreens-minutes#ins06)

**PROPOSED RESOLUTION:** For #341, make `navigator.presentation` attribute mandatory to align with the normative prose.
