### ISSUE TITLE
Presentation display availability is not clearly defined

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#342]
The term _presentation display availablity_ is defined in the introduction to 6.4 [1] but is not clearly defined.  It's not used elsewhere in the spec it seems so it could be dropped, or a sentence could be added to Idioms to clarify it.

[1] http://w3c.github.io/presentation-api/#interface-presentationavailability

**Comment by tidoust** [comment]
See [discussion at TPAC](http://www.w3.org/2016/09/22-webscreens-minutes#ins05)

**ACTION:** @mfoltzgoogle to check that there is a proper definition of "availability".
