### ISSUE TITLE
Establishing a presentation connection steps do not handle failures

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#343]
The steps to establish a presentation connection don't define what happens if the attempt to connect fails.  We might want to do that so there is a way for reconnect() to return a connection that doesn't reach a connected state.

Also, the non-normative note that begins "If the connection step does not complete" could be more specific about which algorithm(s) can be retried on which connections so the state transitions make sense.

**Comment by tidoust** [comment]
See [discussion at TPA](http://www.w3.org/2016/09/22-webscreens-minutes#ins04)

**PROPOSED RESOLUTION:** For #343, move error handling steps from the start algorithm to the establish a connection algorithm, and remove the note in 6.5.1 about retrying connection establishment.
