### ISSUE TITLE
Spec for PresentationConnectionCloseEvent closeMessage conflicts with note

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#344]
The spec for this event states that,

> When the reason attribute is error, the user agent should set the error message to a human readable description of how the communication channel encountered an error.

But the note in 6.5.2 describes how the user agent should set the message to the beginning of the first failed message.  Perhaps we can tweak the note to include both.

**Comment by tidoust** [comment]
See [discussion at TPAC](http://www.w3.org/2016/09/22-webscreens-minutes#ins03)

**ACTION:** @mfoltzgoogle to update close message examples to conform to spec
