### ISSUE TITLE
Clarify presentation ID generation requirements

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#346]
Step 13 in starting a presentation (generation of presentation id) recommends a specific UUID algorithm.  It would be better to clarify this as a "should" as it is a non-required part of an algorithm marked "must" instead of a generic "recommendation."

**Comment by tidoust** [comment]
See [discussion at TPAC](http://www.w3.org/2016/09/22-webscreens-minutes#ins01)

**ACTION:** @mfoltzgoogle to check how other specs reference UUID generation and adjust the spec accordingly with SHOULD or MUST
