### ISSUE TITLE
Specify 1:n communication between a PresentationSession and multiple connected PresentationSession 

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#36]
In some scenarios the presented page may have active connections to multiple PresentationSessions on other pages.  In a gaming scenario, each connected session would represent a game player.  Some information (like dealing a card into the hand) should be sent to one player, while other information (playing a card face up) should be sent to all players.

We need to specify:
(1) How the presented page may communicate to a specific connected page
(2) How the presented page may broadcast - communicate to all specific connected pages

**Comment by anssiko** [comment]
Made this P3 per @mfoltzgoogle's input at http://lists.w3.org/Archives/Public/public-webscreens/2014Dec/0011.html.

**Comment by mfoltzgoogle** [comment]
I am merging this into #19, since I think the two behaviors (connection/disconnection of multiple sessions and messaging among them) will be hard to separate in the specification.
