### ISSUE TITLE
It is unclear what "If there is already an unsettled Promise from a previous call to start for the same controlling browsing context" means"

### ISSUE THREAD

**Issue by smaug----** [w3c/presentation-api#364]
"If there is already an unsettled Promise from a previous call to start for the same controlling browsing context, return a Promise rejected with an OperationError exception and abort all remaining steps. "

Does that mean any PresentationRequest.start() call, or just if the same start() has been called before and promise is unsettled?

**Comment by mfoltzgoogle** [comment]
The intention was to allow the user agent to use modal UI for display selection.  In that scenario, it would be complicated to support simultaneous requests, or confusing to service one request immediately after the other.

I'll craft a PR along the lines of,

> If there is already an unsettled Promise from a call to `start()` on any PresentationRequest in the same controlling browsing context, return a new `Promise` rejected with an `OperationError` exception and abort all remaining steps.

Alternatively, we could convert this step to an implementation note that browser is allowed to use modal UI for display selection and allowed to reject a simultaneous `start()` request according to the constraints of that UI.)

**Comment by mfoltzgoogle** [comment]
@smaug--- if you have further feedback feel free to append it to this issue.  Otherwise I'll assume the PR addressed it.
