### ISSUE TITLE
Investigate if sandboxing flag check can move to the PresentationRequest ctor

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#379]
Follow-up from Issue #362.  It may be possible to check the sandboxing flag in the ctor for PresentationRequest, and this would simplify the algorithms that check it on function invocation.

However, if the attribute is dynamic or set on navigation, it may not be possible.

@mounirlamouri can you update this with what you discover in Blink?

**Comment by mounirlamouri** [comment]
Looking at Blink code, it seems to be dynamic. My understanding of the spec is that it's not.

@annevk do I misinterpret the spec?

**Comment by annevk** [comment]
I don't really understand the sandboxing setup. Too much forwarding of state.

**Comment by mfoltzgoogle** [comment]
Well, it would be safest to check it in both the `PresentationRequest` ctor and its functions.
