### ISSUE TITLE
Filling out the list of available presentation displays for start

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#387]
Step 7. of the [select a presentation display algorithm](http://w3c.github.io/presentation-api/#dfn-select-a-presentation-display) tells the user agent to [monitor the list of available presentation displays](http://w3c.github.io/presentation-api/#dfn-monitor-the-list-of-available-presentation-displays). This is meant to fill out the [list of available presentation displays](http://w3c.github.io/presentation-api/#dfn-list-of-available-presentation-displays), which needs to be non empty for the display selection to do something.

The monitoring algorithm fills out that list based on the contents of the [set of presentation availability objects](http://w3c.github.io/presentation-api/#dfn-set-of-presentation-availability-objects). Problem is that set is only filled out by the [`getAvailability` algorithm](http://w3c.github.io/presentation-api/#getting-the-presentation-displays-availability-information).

In short, if an app calls `start` without first calling `getAvailability`, the monitoring algorithm will simply create an empty list of available presentation displays which would make `start` end up with a `NotFoundError` exception.

I guess the easiest way to fix that would be to have the selection algorithm set the presentation display availability right before current step 7, as done in `getAvailability`. Something like:

7. If the presentation display availability for presentationRequest is null, then:
  - Set the presentation display availability for presentationRequest to a newly created PresentationAvailability object, and let A be that object. 
  - Set the value property of A as follows: 
    1. false if the list of available presentation displays is empty. 
    2. true if there is at least one available presentation display for some member of presentationUrls. That is, there is an entry (presentationUrl, display) in the list of available presentation displays for some presentationUrl in presentationUrls. 
    3. false otherwise. 
  - Create a tuple (A, presentationUrls) and add it to the set of presentation availability objects.
8. If the user agent is not monitoring the list of available presentation displays, run the steps to monitor the list of available presentation displays in parallel.

Now, in theory, there should be no reason to introduce `PresentationAvailability` objects in `start`. Oh well...

**Comment by tidoust** [comment]
Hmm, a better fix might be to complete the monitoring algorithm with a step such as:

If there is a pending request to select a presentation display, run the following step:
  1. For each display in newDisplays, if display is an available presentation display for one of the presentation urls then run the following steps:
     - let presentationUrl be that presentation url
     - Insert a tuple (presentationUrl, display) into the list of available presentation displays, if no identical tuple already exists.

**Comment by mfoltzgoogle** [comment]
We could just have a step in start() before 7 that creates an availability object for the request, and a cleanup step to remove the object.  Then monitoring would run and insert any available displays into the list for the request URLs.

**Comment by mfoltzgoogle** [comment]
Should be addressed by PR #387.
