### ISSUE TITLE
Make select algo reject in ancestor and descendant browsing contexts

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#394]
The [select a presentation display](https://w3c.github.io/presentation-api/#selecting-a-presentation-display) algorithm rejects the Promise "if there is already an unsettled Promise from a previous call to start on any PresentationRequest in the same controlling browsing context".

This is done to allow only one user prompt to select a presentation display at a time for a given tab. However, since `start` can be called by nested browsing contexts as well, I think "the same controlling browsing context" does not capture the notion of "tab" that we need.

There does not seem to be a term to say "all the browsing contexts that compose the tab" in HTML:
http://www.w3.org/TR/html51/browsers.html#nested-browsing-contexts

We could perhaps say "Let top be the [top-level browsing context](http://www.w3.org/TR/html51/browsers.html#top-level-browsing-context) of the current browsing context. If there is already an unsettled Promise from a previous call to start on any PresentationRequest in top or in the [list of the descendant browsing contexts](http://www.w3.org/TR/html51/browsers.html#list-of-the-descendant-browsing-contexts) of top..."

Issue initially raised in: https://github.com/w3c/presentation-api/pull/392#discussion_r92910190

**Comment by mfoltzgoogle** [comment]
CC @imcheng

First, after talking over the possibilities internally, we couldn't come up with a compelling use case for the ability to start multiple presentations across multiple related frames from the same user gesture.  When we discussed multiple display support F2F, we concluded that this use case is better served by having two distinct invocations of `start()` behind different event handlers (Issue #40), so re-entrant use of `start()` should remain unsupported, even across parent/child frames.

As for phrasing, your suggestion sounds fine.
