### ISSUE TITLE
Make sure all IDL members have "dfn" in prose

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#397]
ReSpec shipped a new feature yesterday that warns about missing definitions in prose for IDL members.

ReSpec now reports 25 warnings on the Presentation API, some of them we should fix (e.g. `binaryType`, `connection` properties). Now, ReSpec also complains about the interface names themselves, where it makes sense to me to have the IDL **be** the definition, as done in the Presentation API. I filed an issue against ReSpec: https://github.com/w3c/respec/issues/997

**Comment by mfoltzgoogle** [comment]
I believe this should be addressed by PR #403.
