### ISSUE TITLE
Sandboxing steps in start, reconnect, getAvailability are now useless

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#398]
Now that the `PresentationRequest` constructing steps also check sandboxing flags, I do not see any way to get into a situation where these flags need to be checked again in `start`, `reconnect`, or `getAvailability`.

When we discussed that, I thought sandboxing flag attributes could be changed on-the-fly. I was wrong, there is a warning in HTML5 which says: "These flags only take effect when the nested browsing context of the iframe is navigated. Removing them, or removing the entire sandbox attribute, has no effect on an already-loaded page":
http://www.w3.org/TR/html51/semantics-embedded-content.html#element-attrdef-iframe-sandbox

Now, these steps are essentially harmless, so we could leave them. They are just no-op in practice and could be dropped.

**Comment by mfoltzgoogle** [comment]
Addressed by PR #399.
