### ISSUE TITLE
Screen availability mechanism for multiple sessions

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#40]
## Description
A user may have more than one second screen available and an application may want to take advantage of all these screens at once. However, as things stand, such an application:

1. cannot tell whether there is another unused screen available
1. cannot force the user to select another unused screen when it calls `startSession` a second time
1. cannot tell the user that it wants to connect to multiple screens at once (but note that is covered by #1)

## Proposal
Improve the `screenavailable` mechanism so that the flag reflects the presence of unused second screens at any time?

## References
See initial discussion in https://lists.w3.org/Archives/Public/public-secondscreen/2015Jan/0012.html
See also #1 (multi-display support) and #39 (resumption of multiple sessions)

**Comment by anssiko** [comment]
PROPOSED RESOLUTION: no change to the spec, we may want to provide informative guidelines to the implementors on the screen picker UI with regard to best practices for highlighting screens that are already used by other presentation sessions, clarify we do not support multiple screen selections from the screen picker UI

**Comment by tidoust** [comment]
See relevant discussion at F2F:
http://www.w3.org/2015/05/20-webscreens-minutes.html#item03

**Comment by mfoltzgoogle** [comment]
Commit 7d4929c38fbf5b507b66c93dba22bb8586b0281f amends the note about the selection of the presentation display to mention the multiple-displays case (along the lines of https://github.com/w3c/presentation-api/issues/40#issuecomment-103814798).

It also removes an obsolete issue mentioned inline (which should be addressed by the current spec).

Closing this (long overdue) resolved issue :)
