### ISSUE TITLE
Reference to WebIDL

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#408]
This issue is a follow-up to issues #295 (Check references category and stability) and #407 (drop [SameObject] for promise attribute).

Per process, normative references in the Presentation API should switch to stable specifications en route to Proposed Recommendation. At the time of writing, WebIDL Level 1 is a Recommendation, WebIDL Level 2 is an Editor's Draft. Reference should in theory be to Level 1 (except for NotAllowedError, defined in Level 2), as in the current draft of the Presentation API.

However, there are a number of known issues with Level 1. Can the Presentation API only reference Level 2 or WebIDL without level?

**Comment by mfoltzgoogle** [comment]
Not sure who can answer this question?

**Comment by anssiko** [comment]
@mfoltzgoogle, I think what @tidoust wanted to ask from the technical perspective is:

Does the WebIDL Editor's Draft at https://heycam.github.io/webidl/ (aka "WebIDL without level") have all the definitions the Presentation API needs?

Based on my assessment that is the case, so here's a proposed fix, PR #411.

I believe @tidoust has an open action via https://github.com/w3c/presentation-api/issues/295#issuecomment-272212292 to ensure referencing WebIDL Editor's Draft like this will not block the Proposed Recommendation publication (when we get there). Regardless, referencing "WebIDL Editor's Draft" will not block the update to the Candidate Recommendation tracked in #406.

(Confusion probably arises from the fact that the [WEBIDL-2] reference in the biblio database points to the "WebIDL Editor's Draft" at https://heycam.github.io/webidl/. However, there is no formal "WebIDL Level 2" spec.)
