### ISSUE TITLE
[ReSpec] Performance regression when loading spec over file:///

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#412]
In Chrome 57.0.2987.54, when loading the spec from local disk, the sidebar controls load, then the page is blank for 30 seconds, then the spec is rendered.  This does not  happen when loading from https://w3c.github.io.

- From the devtools profiler, script is not doing anything.
- No request is hitting the network - all subresources are cached.
- The following are printed in the console:
```
 respec-w3c-common:13 Uncaught (in promise) DOMException: The user denied permission to access the database.
r @ respec-w3c-common:13
(anonymous) @ respec-w3c-common:13
respec-w3c-common:2 Plugin core/biblio took too long. Object {name: "core/biblio", done: Promise, resolveRef: function, run: function, stringifyReference: function…}
(anonymous) @ respec-w3c-common:2
respec-w3c-common:2 Error: Plugin core/biblio took too long.
    at respec-w3c-common:2
(anonymous) @ respec-w3c-common:2
n @ respec-w3c-common:1
(anonymous) @ respec-w3c-common:1
e.(anonymous function) @ respec-w3c-common:1
r @ respec-w3c-common:2
(anonymous) @ respec-w3c-common:2
respec-w3c-common:2 Plugin  took too long. Object {run: function}
(anonymous) @ respec-w3c-common:2
respec-w3c-common:2 Error: Plugin  took too long.
    at respec-w3c-common:2
(anonymous) @ respec-w3c-common:2
n @ respec-w3c-common:1
(anonymous) @ respec-w3c-common:1
e.(anonymous function) @ respec-w3c-common:1
r @ respec-w3c-common:2
(anonymous) @ respec-w3c-common:2
````

So maybe this is a permissions problem with accessing IndexedDB in the `core/biblio` plugin?  Does anyone know who maintains it?

**Comment by anssiko** [comment]
Ping @marcoscaceres our chief ReSpec maintainer. Regression possibly introduced by performance improvements rolled into production last month: https://lists.w3.org/Archives/Public/spec-prod/2017JanMar/0005.html

@mfoltzgoogle A workaround is to use localhost for development.

**Comment by marcoscaceres** [comment]
I'll take a look. Please note that specref seems to be down today, which may be the cause

**Comment by anssiko** [comment]
@marcoscaceres This was reported three days ago, so today's downtime probably was not the cause. Note this is not a high priority issue since we have a known workaround.

**Comment by marcoscaceres** [comment]
@mfoltzgoogle, I was not able to reproduce locally (i.e., works for me in all browsers).  Maybe needs a "hard refresh"?

**Comment by mfoltzgoogle** [comment]
After some sleuthing this happens when the "block third party cookies" setting is enabled in Chrome.  Chrome treats each file:/// URL has having a unique origin - trying to access an IndexedDB from a file:/// URL seems to be blocked as "cross-origin."  I do not know if this is intentional or not.

Workarounds:
1. Enable third-party cookies.
2. Fire up a local HTTP server.

Either way I don't think this is something that ReSpec can be expected to fix, although a tip in the README might be helpful in case other editors encounter this.

**Comment by anssiko** [comment]
@mfoltzgoogle, thanks for debugging! I suggest you open an issue at https://github.com/w3c/respec/issues with your findings or edit docs at https://github.com/w3c/respec/wiki directly, and when done close this issue.

**Comment by mfoltzgoogle** [comment]
Edited the Wiki to note incompatibility with file: URLs and IndexedDB.
