### ISSUE TITLE
Make the Example section more concise

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#42]
As we make progress with the spec and the normative sections begin to be self-contained, we may want to carve out the now very extensive Requirements and Example sections into its own "Use Cases and Requirements (and Examples)" document we can evolve in tandem with the API specification at a later stage, referenced from the API spec. Perhaps leave one concise example in the spec.

**Comment by anssiko** [comment]
After @mfoltzgoogle's good changes to the spec to map GitHub issues to the spec, I think we should keep the use cases and requirements in the spec, since they provide good background information, especially for new people reviewing the specification who have not been in the group (or in the Community Group) from its start.

However, I feel the Example section is still too elaborate currently, and requires more work as we progress along the Rec Track. To that end, I'll rescope this issue and rename to "Make the Example section more concise".

**Comment by mfoltzgoogle** [comment]
We could include a smaller code snippets showing how to start/connect to a presentation, and eliminate the prose that has become redundant with the algorithm descriptions in the API section (after addressing the open issued described).

**Comment by anssiko** [comment]
I agree with @mfoltzgoogle in that we should include smaller code snippers in the Example section, and eliminate the prose as it becomes redundant. Optimally, the API is self-documenting to the extend no extensive developer documentation is needed to understand otherwise well-documented example code.

I will unassign myself from this issue, since I think this would be a good first issue for someone new to take who'd like to contribute to the Example section directly.

All - Feel free to assign this issue to yourself, if you'd like to help with this issue in the near future.

Writing code examples against the API and keeping them up to date as the API evolves is a good practise as it prevents surprises with developer ergonomics, helps identify functional issues and spec bugs before the actual implementation feedback is received.

**Comment by louaybassbouss** [comment]
@anssiko you can assign this task to me I am this week on business trip I will work on it on Monday next week

**Comment by anssiko** [comment]
@louaybassbouss Thanks for volunteering. You should be able to click the "assign yourself" link visible on the desktop version of the site (not visible in the mobile version, apparently).

**Comment by louaybassbouss** [comment]
@anssiko it seems that I don't have the rights to assign myself an existing issue

**Comment by louaybassbouss** [comment]
This is the first try for the Examples section. If you receive this as mail notification please open it in Github by clicking on the link at the end of the mail for better formatting.

# Examples

This section shows example codes that highlight the usage of main features of the Presentation API. In these examples, `controller.html` represents the controlling page that runs in the opener user agent and `presentation.html` the presenting page that runs in the presenting user agent. Both pages are served from `http://example.org` (`http://example.org/controller.html` and `http://example.org/presentation.html`). Please refer to the comments in the code examples for further details.

## Monitor availability of presentation displays example

```javascript
<!-- controller.html -->
<button id="castBtn" style="display: none;">  </button>
<script>
  // the cast button is visible if at least one presentation display is available
  var castBtn = document.getElementById("castBtn");
  // availablechange event is fired when the presentation display availability changes
  navigator.presentation.onavailablechange = function(evt){
    // show or hide cast button depending on display availability
    castBtn.style.display = evt.available? "inline" : "none";
  }
</script>
```
            
## Starting a new presentation session example

```javascript
<!-- controller.html -->
<script>
  // it is also possible to use relative URL "presentation.html"
  var presUrl = "http://example.com/presentation.html";
  // create random presId 
  var presId = Math.random().toFixed(6).substr(2);
  navigator.presentation.startSession(presUrl, presId).then(function(newSession){
    // a new session is started successfully
    setSession(newSession);
  },function(){
    // user cancels the selection dialog or an error is occurred
    setSession(null);
  });
</script>
```
         
## Joining a presentation session example

```javascript
<!-- controller.html -->
<script>
  // read presId from localStorage if exists 
  var presId = localStorage && localStorage["presId"] || null;
  // presId is mandatory for joinSession
  presId && navigator.presentation.joinSession(presUrl, presId).then(function(existingSession){
    // session with requested presUrl and presId is found and joined successfully
    setSession(existingSession);
  },function(){
    // no session found for presUrl and presId or an error is occurred 
    setSession(null);
  });
</script>
```
            
## Monitor session's state and exchange data example

```javascript
<!-- controller.html -->
<script>
  var session;
  var setSession = function(theSession){
    // close old session if exists
    session && session.close();
	// remove old presId from localStorage if exists
	localStorage && delete localStorage["presId"];
    // set the new session
    session = theSession;
	if(session){
		// save presId in localStorage
		localStorage && localStorage["presId"] = session.id;
		// monitor session's state
		session.onstatechange = function(){
		  if(this == session && this.state == "disconnected")
		    setSession(null);
		};
		// register message handler
		session.onmessage = function(msg){
		  console.log("receive message",msg);
		};
		// send message to presentation page
		session.postMessage("say hello");	
	}
  };
</script>
```

```javascript         
<!-- presentation.html -->
<script>
  var session = navigator.presentation.session;
  session.onstatechange = function(){
    // session.state is either 'connected' or 'disconnected'
    console.log("session's state is now", session.state);
  };
  session.onmessage = function(msg){
    if(msg == "say hello")
        session.postMessage("hello");
  };
</script>
```

**Comment by anssiko** [comment]
@louaybassbouss Thanks, this looks great and I'd suggest we integrate this into the spec as is. Would you like to submit a PR (help in setting up the environment at [1]) or prefer the editor to integrate these changes?

[1] https://www.w3.org/wiki/Second_Screen/Work_Mode#Direct_Spec_Contributions

**Comment by louaybassbouss** [comment]
Thx Anssi, Yes I will submit a PR I already set up the environment at [1] on my Computer. I will keep the old Examples section as comment in the document.

**Comment by anssiko** [comment]
@louaybassbouss Thanks, looks great to me. This is an improvement that makes the spec easier to digest for people who may want to submit drive-by feedback and comments, e.g. web developers. We should not underestimate the importance of examples. If we can come up with concise examples to address the key use cases we're probably doing fine. If not, then we should take a look at the API to see whether the abstractions are correct. I think the updated examples show that it'd be the former.

@drott Please feel free to merge this. I think we could drop the commented out old example section altogether to simplify the source since we can find it from the history anyway. But I leave it up to the editor to decide.
