### ISSUE TITLE
Turn SHOULD into MUST for close/terminate messages handling?

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#422]
As I'm reviewing tests prepared by @tomoyukilabs for [close/terminate on the receiving side](https://github.com/w3c/web-platform-tests/pull/5562), there are two SHOULD in the Presentation API that now strike me as odd:

1. "If the user agent receives a signal from the destination browsing context that a PresentationConnection S is to be closed, it SHOULD close the presentation connection S with closed or wentaway as closeReason and an empty closeMessage", in [section 6.5](https://w3c.github.io/presentation-api/#interface-presentationconnection)
2. "When a receiving user agent is to send a termination confirmation for a presentation P, and that confirmation was received by a controlling user agent, the controlling user agent SHOULD run the following steps", in [section 6.5.8](https://w3c.github.io/presentation-api/#handling-a-termination-confirmation-in-a-controlling-user-agent)

Are there good reasons for these not to be MUST clauses? With SHOULD, it means a conforming implementation can reasonably ignore "close" and "terminate" messages it receives from the other end. By contrast, in Web socket, the user agent MUST close the connection if it receives a closing handshake from the other side.

Chrome seems to honour these messages. I haven't checked Mozilla's implementation but I suspect that's the case as well.

I get it we cannot guarantee that these messages reach the other side, but if they do, why ignore them?

**Comment by mfoltzgoogle** [comment]
Yes, this is an oversight and we should update the spec to reflect implementation.

**Comment by tomoyukilabs** [comment]
FYI: As far as I have tested on Chrome Canary for Mac and Firefox Nightly for Android,

- Regarding 1., Both Chrome and Firefox close the presentation connection with `closed` as `reason`.
- Regarding 2.,
  - Chrome _closes_ the presentation connection with `error` as `reason` and `Remove route` as `message`.
  - Firefox _terminates_ the presentation connection.

**Comment by mfoltzgoogle** [comment]
PR #425 should address the spec issue.  @tomoyukilabs, behavior #2 would be a bug and I suspect is an artifact of how we discard the offscreen presentation.

**Comment by tomoyukilabs** [comment]
@mfoltzgoogle Thanks. I leave the test to check terminating a presentation as it is.
