### ISSUE TITLE
Add more explanation to examples

### ISSUE THREAD

**Issue by chrisn** [w3c/presentation-api#435]
I'd like to do some work to improve the examples in section 5, with the aim of making the spec a little more approachable to a web developer audience. Specifically:

- Add an explanatory paragraph that introduces each example, based on the existing code comments
- Refactor the example code, if needed

Note, I'm not proposing any change to normative spec text. If this sounds OK, I'll submit a pull request in the coming weeks.

**Comment by anssiko** [comment]
@chrisn, contributions to the examples section are very welcome. Examples are often overlooked part of web specs and it's great if you can improve the situation for the Presentation API.

My general suggestion would be to make the examples as concise as possible, while still keep them functional, and omit any bells and whistles.

**Comment by mfoltzgoogle** [comment]
Go for it. I think they cover the basic functionality all right, but probably don't explain the "why" very well.

**Comment by mfoltzgoogle** [comment]
The PR should help in this area, thanks for the feedback @chrisn. If there's further work please open a new issue with specific areas that aren't clear.
