### ISSUE TITLE
Present a page that's only available to authenticated users.

### ISSUE THREAD

**Issue by Mathieu-R** [w3c/presentation-api#448]
Hello,

I was wondering if it is possible (and how) to present a page that's only available to authenticated users ?
I'm building an audio streaming web app and I would like to cast the player. However, that page is only available to connected users. Authentication is made through JWT.

If I cast that url on my TV, let's say `/player`, I'm redirected on the authentication page.

Thanks for the help :)

**Comment by louaybassbouss** [comment]
@Mathieu-R  it is not a good practice to handle Authentication on receiver device. As solution to present protected content could be:

- Do authentication on sender device
- Generate token (may expires after some time) and send it to receiver device. 
- receiver application requests content from server using that token. 

If you don't have have full control on receiver application it will be difficult to solve the issue

**Comment by Mathieu-R** [comment]
Thanks ! I'm gonna try this 😄

**Comment by louaybassbouss** [comment]
Great I will close this issue please feel free to re-open it (or new issue) if you have additional questions.
