### ISSUE TITLE
Receiver does not receive the initial message

### ISSUE THREAD

**Issue by Mathieu-R** [w3c/presentation-api#450]
I'm using presentation api to cast a media.
Once I'm connected to the receiver i'm trying to send an initial payload that contains the informations about media.
However the receiver receives nothing. 
Next messages are received though.

As you can see in the code, I'm waiting to be in connected state to send the informations.
Maybe I should wait another event ?
Note : window.\_\_connection\_\_ was just to test message sending in the console.

If you need a repo for bug reproduction : https://github.com/Mathieu-R/streamwave

```js
this.chromecaster = new Chromecaster(url);
this.chromecaster.cast().then(_ => {
  // send information for the receiver
  this.chromecaster.sendTrackInformations();
}).catch(err => console.error(err));
```

```js
// Chromecaster class sample
  async setConnection (connection) {
    return new Promise(async resolve => {
      // 1. disconnect from existing presentation if any
      if (this.connection && this.connection !== connection && this.connection.state !== Chromecaster.CLOSED_STATE) {
        this.connection.close();
      }

      // 2. set the connection, save the presentation id in cache in order to allow reconnection
      this.connection = connection;
      window.__connection__ = connection;
      await set(Chromecaster.CHROMECAST_IDB_KEY, connection.id);

      // event listeners
      this.connection.onmessage = evt => {
        console.log(`message from: ${evt.target.id}. Received: "${evt.data}"`);
      }

      this.connection.onconnect = _ => {
        this.updateUI({chromecasting: true});
        resolve();
      }

      this.connection.onclose = _ => {
        this.connection = null;
        this.updateUI({chromecasting: false});
      }

      this.connection.onterminate = _ => {
        del(Chromecaster.CHROMECAST_IDB_KEY).then(_ => {
          this.connection = null;
          this.updateUI({chromecasting: false});
        });
      }
    });
  }

  cast () {
    return new Promise(async (resolve) => {
      // try to reconnect to old presentation
      const id = await get(Chromecaster.CHROMECAST_IDB_KEY);
      let connection;

      if (!id) {
        this.request.start();
      } else {
        this.reconnect(id);
      }

      // wait until connection is available
      // otherwise we would send data before connection is ready
      navigator.presentation.defaultRequest.onconnectionavailable = async evt => {
        await this.setConnection(evt.connection);
        resolve();
      }
    });
  }

  sendTrackInformations () {
    const state = store.getState();
    const data = {
      type: 'song',
      artist: state.player.artist,
      album: state.player.album,
      track: state.player.track,
      currentTime: state.player.currentTime,
      playing: state.player.playing,
      primaryColor: state.player.primaryColor
    };
    this.send(data);
  }

  send (data) {
    if (!this.connection) {
      console.warn('[Presentation API] no active connection...');
      return;
    }

    this.connection.send(JSON.stringify(data));
  }
```

Thanks for your help.

**Comment by mfoltzgoogle** [comment]
@imcheng Thanks for the report.  The `connectionavailable` event is only fired if the default request is started by the browser.  

- Are you starting the presentation by calling start() in the page or by starting it from the browser via the default request?
- Are you assigning `navigator.presentation.defaultRequest` somewhere else in your code?  I don't see an assignment.

I am travelling at the moment but may be able to examine the rest of your application when I return.

**Comment by Mathieu-R** [comment]
@mfoltzgoogle 
- I am not sure I really understand your first question. As the user click on the chromecast button, I'm calling `start()` as you can see in the `cast() method`.    
- Yes, in the constructor, something like : 
```js
this.request = new PresentationRequest(url);
navigator.presentation.defaultRequest = this.request;
this.monitorPresentationAvailability();
``` 

@louaybassbouss Yes, i'm aware of that but I'm only using presentation API with Chrome Desktop.

**Comment by imcheng2** [comment]
@Mathieu-R 
- It looks like your code waits for connected state before sending message. Can you just add another check in the send() method just to be extra safe?
- If it is indeed not sending message through in connected state, then can you provide your Chrome version? It would also be good to try on Chrome Canary and/or different Chrome channels to help us narrow down the issue.

**Comment by Mathieu-R** [comment]
@imcheng2 
Thanks for checking the issue.
My Chrome version is : `66.0.3359.181`.

**Comment by tomoyukilabs** [comment]
@Mathieu-R Those codes to handle connections seem confused. Basically, we can start a presentation by either of the following steps:

1. Create a presentation request and call `request.start()`
2. Set a presentation request to `navigator.presentation.defaultRequest` and **click a cast button or menu on the browser's GUI**
<img width="298" alt="screen shot 2018-05-23 at 16 37 56" src="https://user-images.githubusercontent.com/3643972/40410433-c8b0b65c-5ea8-11e8-8abe-928ec45afc26.png">

Then, a presentation connection will be passed via:

- the Promise returned by `request.start()`, in the case of 1.
- the `connectionavailable` event, in the case of 2.

So the following examples are my suggestion:

```js
      if (!id) {
        this.request.start();
      } else {
        this.reconnect(id);
      }
```

These should be corrected like:

```js
      let connection;
      if (!id) {
        connection = await this.request.start();
      } else {
        connection = await this.reconnect(id);
      }
      await this.setConnection(connection);
      resolve();
```

And then,

```js
      // wait until connection is available
      // otherwise we would send data before connection is ready
      navigator.presentation.defaultRequest.onconnectionavailable = async evt => {
        await this.setConnection(evt.connection);
        resolve();
      }
```

These codes should be called in the constructor (after `navigator.presentation.defaultRequest = this.request;`), rather than in `cast()` method.
