### ISSUE TITLE
Update Status of This Document

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#47]
The "Status of This Document" section should be updated before we publish FPWD:

http://w3c.github.io/presentation-api/#sotd

IIRC @tidoust volunteered to take this.

**Comment by anssiko** [comment]
Before we publish FPWD, I believe it would be helpful to note in the Status of The Document section [1] that the group uses GitHub for issue tracking. Currently, the spec has 27 open issues in GitHub [2]. Some issues are inline in the spec to provide more context around them (and that's fine), thus it may not be obvious to people outside the group reviewing the spec that they should also be looking at GitHub issues. I suggest we keep the "Participate" header too, perhaps make it a list as some other specs have done with appropriate pointers, such as:

Participate:
Mailing list
GitHub repository
Open issues
Commit history

Secondly, to set the expectations with regard to maturity, we could state something like:

This document is not complete and is subject to change. Feedback from early experimentations is
encouraged to allow the Second Screen Presentation Working Group evolve the specification based on implementation feedback.

[1] http://w3c.github.io/presentation-api/#sotd
[2] https://github.com/w3c/presentation-api/issues

**Comment by mfoltzgoogle** [comment]
The following text has been added to the Status of The Document to reflect that GH is the source of truth for open issues.

> This document is a work in progress and is subject to change. It builds on the final report (dated 18 November 2014) produced by the Second Screen Presentation Community Group
> ...
> A few open issues are noted inline. Please check the group's issue tracker on GitHub for an accurate list. 

Therefore, closing this issue.
