### ISSUE TITLE
PresentationRequest is not defined?

### ISSUE THREAD

**Issue by crysta-l** [w3c/presentation-api#475]
there is no problem in my local project, and it works well. but when I build it to the test development environment and the console panel will warn. and then I changed the host add www.test.com like this
![image](https://user-images.githubusercontent.com/7333148/67548181-c6126d80-f733-11e9-8f9f-b1aafd79e533.png)

www.test.com
![image](https://user-images.githubusercontent.com/7333148/67546963-48009780-f730-11e9-946e-6370e50dad3b.png)
 
127.0.0.1:8080
![image](https://user-images.githubusercontent.com/7333148/67548135-a3805480-f733-11e9-8c3a-870fe6c8a61e.png)

I can't find any answer, could any one can answer me?
my Chrome version 76.0.3809.100

**Comment by crysta-l** [comment]
Here is my code, The framework I am using is vue
![image](https://user-images.githubusercontent.com/7333148/67548684-feff1200-f734-11e9-82fb-b8d6f421a1a4.png)

**Comment by mfoltzgoogle** [comment]
@crysta-l Sorry for the delayed response.  Can you make sure that navigator.presentation is defined?  Also, what is the value of `window.isSecureContext`?  If it is not true, then the Presentation API is not available for that frame/document.

If you are still having problems with using the Presentation API in Chrome, please file an issue at https://bugs.chromium.org/p/chromium/issues/entry and assign it to mfoltz@chromium.org.  (If you set the component to Blink>PresentationAPI, it will end up in the proper bug queue, but as long as I see it, I can fix that for you.)  Thanks!

I'm closing this out as it looks like an application/browser issue and not a spec issue.
