### ISSUE TITLE
Requesting enhancements to the presentation API

### ISSUE THREAD

**Issue by rdrrichards** [w3c/presentation-api#477]
Hello,

I would like to propose a couple of enhancements to the presentation API. Is this the place where I would do that? Or, is there another forum more appropriate for that sort of thing?

Specifically, I would like propose that we be allowed to start a presentation in a window that is not a incognito, or in-private, so we can give the end user a better experience when the application being presented requires something like SSO authentication. 

Another enhancement would be that we be able capture the presentation device that end users chose, and that we can automatically use that same device in future presentation requests, if the device is available.

If this is the place to post that sort of thing, I will do that in other, more detailed posts.

Thanks for your help.

**Comment by mfoltzgoogle** [comment]
Hi @rdrrichards, yes, this is the right forum for making these requests.  Sorry it took a while to get back to you!

> Specifically, I would like propose that we be allowed to start a presentation in a window that is not a incognito, or in-private, so we can give the end user a better experience when the application being presented requires something like SSO authentication.

This is a use case that we have discussed in Issue #347, that would open a presentation window as a child of the current window (like `window.open()`), which would share cookies browser state with the parent.

A couple of things I would like to ask, is whether it's important for your use case that:
- The presentation window be shown on remote (wireless) displays as well as local, secondary monitors
- The presented content has to be rendered in a new document, or if the presented content could be rendered in a frame/element of the original page.

> Another enhancement would be that we be able capture the presentation device that end users chose, and that we can automatically use that same device in future presentation requests, if the device is available.

That's an interesting idea.  This is something that the browser's user interface could support, for example by clicking a box saying "always use this device for this site."

Or were you thinking of having two buttons on your site, one to connect to the previous presentation device, and another to choose a new presentation device?

**Comment by rdrrichards** [comment]
Hey @mfoltzgoogle,

Thanks for getting back with me! 

To address your questions:

- Local, secondary monitors fit the use case in the situation I have in place.
- The content should be rendered in a new document.

The use case I have been using the Presentation API for is this: we have a primary application that starts a presentation. We have a secondary application that is presented, and that is an Angular application that we use to control navigation; it hosts an iframe that shows yet another application which uses SSO authentication. The connection between the primary and secondary applications via the presentation API allows us to switch application context on both sides simultaneously. It all works quite well, accept that we must re-authenticate because the secondary application opens in an incognito window. The goal is to get the authentication steps to a minimum. I hope that is clear, and helps you understand the need.

For the other request concerning capturing the presentation device for later reuse; I really like the idea of having a checkbox saying, "always use this device for this site." That would work perfectly for what I am thinking. Excellent idea!

I would appreciate hearing about any progress toward making these a reality. Thank you!

**Comment by michaelwasserman** [comment]
@rdrrichards, this use case may fit nicely within the scope of a separate [Multi-Screen Window Placement](https://github.com/webscreens/window-placement) proposal. Please see this recent [web.dev blog post](https://web.dev/multi-screen-window-placement/), which describes how to test prototype functionality by enabling a Chrome flag or obtaining an Origin Trial token, and check out this [basic demo](https://michaelwasserman.github.io/window-placement-demo/). Let us know what you think, and feel free to share feedback by filing an issue on that proposal's repo. Hope that helps!

**Comment by rdrrichards** [comment]
@michaelwasserman This looks very promising! I will start to evaluate this in a test application I have, and provide feedback.

Thank you.

**Comment by anssiko** [comment]
@rdrrichards, did the [Multi-Screen Window Placement](https://github.com/webscreens/window-placement) proposal satisfy your requirements with respect to SSO authentication, or were you able to work around the issue otherwise? Please let us know.

**Comment by rdrrichards** [comment]
@anssiko I have no doubt that the proposal will satisfy my requirements with respect to SSO authentication. The only thing I really have to work out is the appropriate tool to use for window to window browser communication. Working on that now...

**Comment by anssiko** [comment]
@rdrrichards, thanks for confirming the Multi-Screen Window Placement proposal satisfies your requirements.

I'll close this feature request for the Presentation API. Thanks for checking in with us!
