### ISSUE TITLE
reconnect after termination

### ISSUE THREAD

**Issue by jimmywarting** [w3c/presentation-api#480]
usecase: At home i never watch anything on Netflix on my computer since i have a ChromeCast. So i always connect to my TV at home - except for when i look at trailers. But i think it would have been nice if i didn't have to be prompted all the time to select the same remote playback.

I just tested the presentation api a bit and found out that you could reconnect to a device with the `connection.id` but it becomes obsolete after a termination. I wish it could be more persistent

**Comment by mfoltzgoogle** [comment]
Thanks for the feedback @jimmywarting.  Applications that wish to keep the presentation (content on the TV) running can `close()` their connection and use the `id` to reconnect later.  But `terminate()` always tells the remote presentation to be terminated (so there's nothing to reconnect to).

Whether the site reconnects automatically or not as you move between pages/videos is largely up to the site.  I think netflix.com does a pretty good job of this, but if you are encountering behavior you think is wrong on Chrome please file a bug [here](https://bugs.chromium.org/p/chromium/issues/entry) and assign it to the `Blink > Presentation API` component.

Thanks!

**Comment by jimmywarting** [comment]
> Whether the site reconnects automatically or not as you move between pages/videos is largely up to the site. I think netflix.com does a pretty good job of this.

netflix dose a good job on sessions (even syncing it between PC and Mobile). But i wish I wouldn't have to reconnect the next day or after i have shut down the browser/pc
