### ISSUE TITLE
Publish a Candidate Recommendation Draft

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#488]
>RESOLUTION: Look into publishing a new CR for the Presentation API

via https://www.w3.org/2020/10/20-webscreens-minutes.html#r02

Per @tidoust's post-meeting note we can publish a Candidate Recommendation Draft right away under the new process.

@mfoltzgoogle, nice to have prior to the CRD publication would be an update to the [change log](https://w3c.github.io/presentation-api/#change-log). Alternatively, we could link to the commit log. The former is probably a bit friendlier for readers who are not following the spec development closely.

**Comment by mfoltzgoogle** [comment]
I'm happy to update the changelog.   I will land #487 first so it can be included in the CRD.

Also, do we need to resolve #486 (updating cross references) first?  I will review that issue, but it sounds like it may require cooperation from other groups/specs to fully resolve.

**Comment by tidoust** [comment]
> Also, do we need to resolve #486 (updating cross references) first? I will review that issue, but it sounds like it may require cooperation from other groups/specs to fully resolve.

It would be good to fix the cross references that are currently broken because the terms no longer exist (and notably the notion of "allowed to show a popup").

It seems ok for now to continue to reference terms from other specs that do not yet have an export flag, while we discuss a proper resolution with other groups. I'll update the PR so that it may be merged.

**Comment by anssiko** [comment]
@tidoust, I believe the spec is now ready for CRD publication sans metadata tuning. CfC to publish is recorded in the [20 Oct minutes](https://www.w3.org/2020/10/20-webscreens-minutes.html#r02) and 10 working days have passed. Feel free to proceed with the CRD publication.

**Comment by tidoust** [comment]
Sure! I issued a couple of pull requests to update the Status of this Document section (#491) and update a few links (#492) to pass pubrules validation.

**Comment by tidoust** [comment]
And one last one around use of inclusive terminology (#493). That should be all we need.

**Comment by tidoust** [comment]
The spec has now been published as a Candidate Recommendation Draft at:
https://www.w3.org/TR/2020/CRD-presentation-api-20201105/

That new version is returned when one retrieves:
https://www.w3.org/TR/presentation-api/
(A cache refresh may be needed to get the new version though)
