### ISSUE TITLE
Update the link to the HTTP spec

### ISSUE THREAD

**Issue by xfq** [w3c/presentation-api#517]
https://www.w3.org/TR/presentation-api/#terminology

> The header Accept-Language is used as [defined in HTTP/1.1](https://tools.ietf.org/html/rfc7231#section-5.3.5) [[rfc7231](https://www.w3.org/TR/presentation-api/#bib-rfc7231)].

RFC 7231 has been obsoleted by [RFC 9110](https://datatracker.ietf.org/doc/html/rfc9110).

**Comment by mfoltzgoogle** [comment]
Closed by #518.

**Comment by xfq** [comment]
Thank you!
