### ISSUE TITLE
Specify the NavigatorPresentation.session attribute and its related algorithms

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#52]
[Migrating the following inline issue from the spec into the issue tracker:]
> The purpose of the session attribute is to provide the presented page with access to the PresentationSession without allowing a potential race condition between the registration of an event handler and the firing of an event, or complicating the browser implementation to fix this case. It should be null in an opening context and non-null in a presented document.

**Comment by mfoltzgoogle** [comment]
The session attribute was removed by PR #122, which also defines the algorithm for exposing the PresentationSession to the presenting browsing context.  I believe this issue can also be closed.
