### ISSUE TITLE
Presentation API publication is failing with echidna error

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#521]
The [last attempt to publish the spec](https://github.com/w3c/presentation-api/actions/runs/10516928404/job/29140103131) failed [with an error that I'm not familiar with](https://labs.w3.org/echidna/api/status?id=40c08871-97cf-445c-b870-e107620c8d6c):

```
"specberus": {
        "status": "failure",
        "errors": [
          {
            "key": "not-participating",
            "extra": {
              "id": 63802
            },
            "detailMessage": "The user with id 63802 is not participating in the group producing this document.",
            "type": {
              "name": "headers.editor-participation",
              "section": "front-matter",
              "rule": "editorSection"
            }
          }
        ]
      },
```

I see that Dominik (former editor) has a w3cid of 63802, maybe that is what echidna is complaining about?

```       
 editors: [
          {
            w3cid: 68454,
            name: 'Mark Foltz',
            company: 'Google',
            mailto: 'mfoltz@google.com'
          },
          {
            w3cid: 63802,
            name: 'Dominik Röttsches',
            company: 'Intel',
            note: 'until April 2015'
          }
        ],
```

Calling on @tidoust for his expertise in all things around spec publishing :)

**Comment by anssiko** [comment]
@mfoltzgoogle thanks for debugging this! #522 was an appropriate fix in this case; spec-prod says [success again](https://labs.w3.org/echidna/api/status?id=c3e6b75b-2065-4eb9-80d4-d49498c881c1).

FTR: specberus started to check editors are group participants in https://github.com/w3c/specberus/pull/1787
