### ISSUE TITLE
Make the "set of presentations" variable global

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#65]
We refer to the variable D in the "Starting a presentation session" algorithm [1] without first declaring and initializing it:

>Add (S.url, S.id, S) to D.

Since we refer to D in many places and it holds global state, we should define D as a global variable, and refer to the global from within related algorithms. Something like:

>Each XXXX has a &lt;dfn&gt;set of presentations&lt;dfn&gt;.

And then link to the global definition from within the algorithms, e.g.:

>Add (S.url, S.id, S) to &lt;a&gt;set of presentations&lt;/a&gt;.

What would be XXXX above i.e. what do we mean by "known by the user agent" specifically? Is the set of presentations associated with the document's origin similarly to e.g. Web Storage [2]? If so, we could reuse some of the prose from that spec and adapt.

[1] http://w3c.github.io/presentation-api/#starting-a-presentation-session
[2] http://www.w3.org/TR/webstorage/#the-sessionstorage-attribute

**Comment by mfoltzgoogle** [comment]
@anssiko, should we leave this issue open until we have updated the rest of the spec to match the style in the PR?

**Comment by anssiko** [comment]
@mfoltzgoogle I think #107 should close this issue. Please review and merge if it looks good to you.
