### ISSUE TITLE
Review the use cases and requirements

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#68]
The Presentation API attempts to address the use cases and requirements outlined in the specification at: http://w3c.github.io/presentation-api/#use-cases-and-requirements-0

We should evaluate the UCs and Reqs we laid out initially, and based on group discussion and consensus see if changes are needed. For example, people working on the implementations may have discovered new requirements that we did not anticipate initially that would be in scope for the group. I propose we discuss this at F2F time permitting, and to make for a productive session, more complete proposals for new use cases and requirements should be provided before the meeting.

**Comment by hongkicha** [comment]
Anssi, we currently have four UCs so why don't we add another category? **Digital Signage(DS)**. <br>DS is a screen media showing contents such as advertisements and notifications. <br>DS is one of the closest media we bump into everyday.<br> I strongly believe Presentation API should support some functionalities DS requires. <br>  In this sense, I would like to...
1. update our document by adding a short description on DS.
2. prepare a not too long presentation on DS at our upcoming F2F meeting.
Your thoughts?

**Comment by anssiko** [comment]
@hongkicha Thanks for volunteering to look at how the Presentation API might be used in digital signages.

To start, I suggest you prepare such a document outside of this repository and provide a link in here. Please note that digital signage specific features are out of scope for this Working Group. Such features are better discussed and specified in the Second Screen Presentation Community Group [1] that is set out to incubate experimental ideas, or in the Web-based Signage Business Group [2], that has produced use cases [3].

Requirements that are deemed generic may motivate changes to the Presentation API. Identifying such generic requirements would be something I'd like to see discussed at F2F in the UCs and Reqs slot to keep the group focused on its Scope [4].

[1] https://www.w3.org/community/webscreens/
[2] https://www.w3.org/community/websignage/
[3] http://www.w3.org/community/websignage/wiki/Web-based_Signage_Use_cases_and_Requirements
[4] http://www.w3.org/2014/secondscreen/charter.html#scope

**Comment by hongkicha** [comment]
@anssiko Thanks Anssi for clarification. Now I got to know more about how our WG actually works. I thought it was fine to introduce DS directly here at WG. I'll get back to this issue soon. Thank you again!

**Comment by anssiko** [comment]
ACTION: Louay to initiate the Use cases and Requirements document (probably on a Wiki page) [recorded in http://www.w3.org/2015/05/19-webscreens-minutes.html#action01]

**Comment by anssiko** [comment]
ACTION: @avayvod to refactor use cases to avoid overlap [recorded in http://www.w3.org/2015/05/19-webscreens-minutes.html#action02]

**Comment by anssiko** [comment]
ACTION: @schien to complete the list of requirements with multiple users ones [recorded in http://www.w3.org/2015/05/19-webscreens-minutes.html#action03]

**Comment by anssiko** [comment]
ACTION: @tidoust to look into WebRTC WG's [Audio Output Devices API](http://w3c.github.io/mediacapture-output/) and its reuse in the context of the Presentation API [recorded in http://www.w3.org/2015/05/19-webscreens-minutes.html#action06]

**Comment by schien** [comment]
Here is the discussion result with @mfoltzgoogle and @avayvod, some wording need further refinement:

**Discovery & availability**
    The UA must provide a way to find out whether at least one secondary screen is available. (note: think of more than one screen if there’s a use case for 1:n case)
    *EDITOR’S NOTE: Spec should clarify that a single physical screen may accept multiple presentations.*
**Launching presentation**
    The UA must provide a way to start sending content to one or many secondary screens from one or more controlling pages. This may occur at the request of the page or at the request of the UA.
Resuming presentation
    The UA must be able to resume an existing session with the content being displayed on the secondary screen.
**Communication**
    The UA must enable exchanging data between the primary and the secondary screen in order to have a control channel between the primary and secondary page. The UA must not make assumptions about the execution locality of the UA of the remote page or pages it communicates with (i.e. the secondary page or pages might run on one or many remote UAs, and thus the link between these two or more pages must be loosely coupled).
**Signaling disconnection**
    The UA must signal disconnection from the presentation page to the primary page and vice versa.
**Many-to-one session**
    The UA should be able to accept multiple incoming sessions within one presentation browsing context. This functionality might not be supported in 1-UA mode because the presentation browsing context is not shareable across devices.

**Comment by mfoltzgoogle** [comment]
I have created the following pull request to update the requirements using a updated version of the text above.  @schien please review at your leisure.

https://github.com/w3c/presentation-api/pull/95

**Comment by louaybassbouss** [comment]
I will start to create a document to collect the use cases and requirements as we agreed in the F2F meeting [recorded in http://www.w3.org/2015/05/19-webscreens-minutes.html#action01]. I would prefer to use a markdown file in this git repository instead of the Wiki. In this case we can use all the features of git/github as for the spec. What do you think?

**Comment by anssiko** [comment]
Markdown is perfectly fine. If the group wants to publish the UCs and Reqs document as a WG Note at a later time, we can convert it into the spec format later on. However, publishing it as a WG Note is not a requirement.

**Comment by avayvod** [comment]
Both thumbs up for Markdown!!!

**Comment by mfoltzgoogle** [comment]
Markdown SGTM as well.

Are we going to move both the requirements and the use cases into the new document?  I don't feel strongly either way, but the requirements in #95 have some cross references into the spec so we'll want to preserve those.

**Comment by louaybassbouss** [comment]
Thx @mfoltzgoogle yes we need to preserve the references into the spec. @anssiko @tidoust do you know another w3c spec where the use cases and requirements are in a separate document?

**Comment by anssiko** [comment]
@mfoltzgoogle The way how the requirements refer the common idioms defined in the spec (#95) is great. You should keep these references as they make the requirements more understandable and concrete.

@louaybassbouss For example, the [Manifest spec][1] has a separate [Use Cases and Requirements document][2]. You may want to keep the top-level section "Use Cases and Requirements" in the spec and just provide a link to the separate document in it.

Later on, when the UCs and Reqs have stabilized we may integrate them into the spec, or publish them as a so-called [WG Note][3] if we want to provide a stable standalone reference.

[1]: http://w3c.github.io/manifest/
[2]: https://w3c-webmob.github.io/installable-webapps/
[3]: http://www.w3.org/2014/Process-20140801/#WGNote

**Comment by tidoust** [comment]
Separating use cases and requirements is indeed not an uncommon pattern, @louaybassbouss. The easiest way to find examples is probably to browse the list of published [technical reports](http://www.w3.org/TR/#w3c_all) and search for "use case" or "requirement".

A few other examples for inspiration:
* The [Packaged Web Apps (Widgets)](http://www.w3.org/TR/widgets/) spec has a separate [landscape](http://www.w3.org/TR/widgets-land/) and a separate [requirements](http://www.w3.org/TR/widgets-reqs/) document
* [Use cases and requirements for Standardizing Responsive Images](http://www.w3.org/TR/respimg-usecases/)
* [Web Audio Processing: Use Cases and Requirements](http://www.w3.org/TR/webaudio-usecases/)

**Comment by hongkicha** [comment]
Thanks @tidoust for the examples. Taking the [Web Audio Processing: Use Cases and Requirements](http://www.w3.org/TR/webaudio-usecases/) document into account, I think we can add more required UC if needed. I have already started writing my [UC](http://www.w3.org/2015/05/20-webscreens-minutes.html#item04) and if @louaybassbouss could create a new document, I'd be glad to update that document as well. :+1:

**Comment by obeletski** [comment]
I'd be happy to contribute with the use cases that cover 1:n communication [1] as well. 
As a side note, from my past experience I have learned that use cases related to gambling and dating are not appropriate for some of the companies/cultures.
[1] https://lists.w3.org/Archives/Public/public-secondscreen/2015May/0035.html

**Comment by anssiko** [comment]
@obeletski Gambling may not indeed be an appropriate use case for a specification (see [gambling in China][1], for example). Please feel free to contribute to and improve the use cases.

[1]: http://en.wikipedia.org/wiki/Gambling_in_China

**Comment by louaybassbouss** [comment]
I just submitted a PR #98 that contains the initial version of the use cases and requirements document. The use cases and requirements are copied form the current spec. The multiplayer game (poker) use case is updated according to issue #27. 
@hongkicha @obeletski please feel free to add your use cases to the document when the PR is merged.

**Comment by mfoltzgoogle** [comment]
The document added in PR #98 is ready to accept new or updated use cases.

**Comment by louaybassbouss** [comment]
I think there are still some TODOs in this task:

* Check mapping between use cases and requirements: the new requirements [REQ06][1] and [REQ07][2] are not referenced from any use case. 
* Do we need a new Requirement for "Joining Presentation"? I think yes but I am not sure if this is already addressed in the new requirement [REQ06: Multiple controllers per presentation][1] defined by @mfoltzgoogle.  IMO if we have requirements for launching or resuming presentation, we should also have a requirement for joining presentation
* What about merging use cases "Video and Image sharing" and "Media Flinging to multiple screens" for example to "Media Sharing and Control". 

Once we agreed on these points, I can update the document and file a new PR.

@hongkicha @obeletski feel free to propose your use cases in this thread

[1]: https://github.com/w3c/presentation-api/blob/gh-pages/uc-req.md#req06
[2]: https://github.com/w3c/presentation-api/blob/gh-pages/uc-req.md#req07

**Comment by louaybassbouss** [comment]
I just submitted a new PR #126  covering the TODOs from my previews comment. 

@mfoltzgoogle before you merge this PR please change in Overview.src.html the link "https://github.com/w3c/presentation-api/blob/gh-pages/uc-req.md#req08-power-saving-friendly" into "https://github.com/w3c/presentation-api/blob/gh-pages/uc-req.md#nf-req01". I tried to change it but I got some errors while compiling the files using `make`

**Comment by mounirlamouri** [comment]
We have a very decent UC and requirements doc. Closing.
