### ISSUE TITLE
The difference between index.html & Overview.src.html

### ISSUE THREAD

**Issue by hongkicha** [w3c/presentation-api#69]
Hi, all. <br> I would like to make some minor editorial changes on our document. <br>I see two very simliar looking files at the master directory: [index.html](https://github.com/w3c/presentation-api/blob/gh-pages/index.html) & [Overview.src.html](https://github.com/w3c/presentation-api/blob/gh-pages/Overview.src.html)
**Could anybody tell me the difference between these two?**
To be more precise,
**Why do we need the spec source (Overview.src.html) and the generated spec (index.html) separately?**
Thanks in advance!

**Comment by louaybassbouss** [comment]
Both documents are similar you should only edit Overview.src.html. Index.html can you generate as described in [Work Mode Document] (https://www.w3.org/wiki/Second_Screen/Work_Mode) in the Wiki

Louay

**Comment by hongkicha** [comment]
@louaybassbouss Thank you for your information. I guess I need to upload both Overview.src.html and index.html. If you don't mind, I'd like to ask one more thing;
Can I ask for pull request using this **GitHub website**? Again, I'd like to know the difference between asking pull request using **the terminal(command line) and GitHub website**.

**Comment by louaybassbouss** [comment]
@hongkicha yes you need to upload both files. Regarding your second question: if you follow the steps described in [How to Contribute via Pull Requests](https://www.w3.org/wiki/Second_Screen/Work_Mode#How_to_Contribute_via_Pull_Requests) --> step9 says "On GitHub, navigate to your fork https://github.com/YOUR_GITHUB_USERNAME/presentation-api and create a pull request with your changes" this means you can create PR using GitHub website. It  worked fine for me. I don´t have experience with equivalent command line in terminal.

**Comment by hongkicha** [comment]
@louaybassbouss Thanks a lot. In fact, I tried both ways for my dummy repository and I couldn't find any difference between these two. That's why I was asking for help. :smiley: 
Anyway Louay, thank you very much and I hope to see you in May.

**Comment by anssiko** [comment]
@hongkicha I updated the README.md to make the Work Mode documentation easier to discover if you land on the GitHub repo directly. The Anolis workflow may not be the most self-documenting, so please let us know if you run into further issues. I'll close this issue now.

**Comment by hongkicha** [comment]
@anssiko Thanks a lot. And of course, thanks to @louaybassbouss I was able to ask for a pull request #73 on minor grammar mistakes. Thanks to both of you!
