### ISSUE TITLE
Timing of availablechange event to signal screen availability

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#8]
From http://webscreens.github.io/presentation-api/#example:

Do we want to fire an event immediately after the page registers for it? What's a best practice method for asynchronous notifications of ths kind?

**Comment by mfoltzgoogle** [comment]
This can be addressed by a small modification to the existing algorithm for `onavailablechange`.  If we fire an `availablechange` event to any handler that is added (regardless of the status of the screen list) then we should be good.

**Comment by schien** [comment]
This issue can be addressed by the API modification introduced in #81.

**Comment by mfoltzgoogle** [comment]
As we have implemented a Promise-based API for retrieving the availability status, I believe that this issue has been addressed.
