### ISSUE TITLE
Define algorithm for browser initiated presentation using default presentation URL

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#86]
Pull request #77 added definitions to the spec for the default presentation URL and ID to allow the UA to initiate presentation on behalf of the page.  This issue tracks an update to the algorithms for 6.4, "Interface NavigatorPresentation" to define the side effects on the UA state when this happens.

**Comment by mwatson2** [comment]
What causes the UA to initiate a session with the default presentation URL ?

**Comment by mwatson2** [comment]
OK, I caught up ;-) The default presentation URL would be used if the user triggers a presentation through the UA rather than through the page.

Is it intended that the default presentation URL is *also* used to filter devices for the purpose or the availabilitychange event ?

**Comment by mfoltzgoogle** [comment]
> Is it intended that the default presentation URL is also used to filter devices for the purpose or the availabilitychange event ?

Yes, @avayvod and I believe it makes sense to do so.  The page has told us what content it wishes to present, so we should event the page only when there are screens available that can show that content.

However, this does raise some privacy concerns so it will need further discussion.

See https://github.com/w3c/presentation-api/pull/87

**Comment by mfoltzgoogle** [comment]
PR #146 and the follow-on commit 586844704b025c416215dccb340f0d7229e17a4e describe the browser's behavior to setting `navigator.presentation.defaultRequest` in http://w3c.github.io/presentation-api/#setting-the-default-presentation-request.

There is an open issue relating to starting a session based on the default request. If the user initiates presentation and has pre-selected a screen, the UA doesn't need to ask the user again in http://w3c.github.io/presentation-api/#dfn-start-a-presentation-session. 

I'm leaving this open until the spec has been adjusted to address that issue.

**Comment by mfoltzgoogle** [comment]
PR #274 adds some text for the case discussed in the previous note.

After some thinking I didn't think it was worth patching the start algorithm to explicitly bypass the "ask permission" step.  As written, I think there is leeway for the user agent to consider the pre-selection of the display (e.g., via tap-to-present) as granting permission, and make its own security/convenience tradeoff.  

I'll update the PR to make this more explicit.

**Comment by mfoltzgoogle** [comment]
PR #274 merged.
