### ISSUE TITLE
Provide session lifecycle management for presenting page

### ISSUE THREAD

**Issue by schien** [w3c/presentation-api#92]
Currently we only provide the session initial/resumption/teardown algorithm for controlling page. Since Mozilla is the first implementation that use HTML5 in presenting side, we'd like to contribute the session management algorithm to spec.

**Comment by anssiko** [comment]
@schien Please feel free to provide a proposal for the group to review in this issue.

**Comment by mfoltzgoogle** [comment]
There are currently algorithms for establishing a presentation connection, closing and terminating a presentation connection and creating a new connection in a receiving browsing context.  There are two open issues I am aware of:

* #222 - define the behavior while receiver calls connection.terminate()
* #229 - Need algorithm for establishing a presentation connection when the previous connection(s) were closed

Let's use those issues and file additional specific ones for improving the specification of the connection lifecycle.  Closing this.
