### ISSUE TITLE
Define behavior of Window and Fullscreen APIs in the presentation browsing context

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#99]
I think some normative statements about the behavior of these APIs should be considered. 

First, APIs that require input or handle focus should be discouraged from being supported:
* alert()
* confirm()
* blur()
* focus()
* print()
* prompt()

APIs that create new browsing contexts also be discouraged, as they are not friendly with 1-UA presentation.
* open()
* createPopup()

APIs that modify the position of the window are also not very meaningful in a reasonable implementation of the 1-UA mode:
* moveTo()
* moveBy()
* resizeTo()
* resizeBy()

Finally, we should support the  [Fullscreen API](https://fullscreen.spec.whatwg.org/), as web developers may want to use related CSS features as well as ensure fullscreen rendering of `<video>` content.  However, we may need to patch the Fullscreen spec for this scenario - need to dig further.

**Comment by mounirlamouri** [comment]
I guess we could add the Presentation API in this list of APIs?

**Comment by hsablonniere** [comment]
@mounirlamouri To prevent some kind of inception ? :smile:

**Comment by hsablonniere** [comment]
@mfoltzgoogle I totally agree on the list of discouraged APIs but what would you enable from the CSS Fullscreen API?

Maybe we could have `:fullscreen` on the html element of the presentation browsing context but what about `::backdrop`? I'm not sure it makes sense to support it.

**Comment by hsablonniere** [comment]
Isn't the presentation browsing context already displayed  in fullscreen?

**Comment by mfoltzgoogle** [comment]
@mounirlamouri Well, the part of the API for receiving the PresentationSession is necessary for the page to communicate to the controller.

As for the controlling side, Jonas brought up the idea of a presentation "daisy chaining" onto additional screens to display alternate content.  See commit  https://github.com/w3c/presentation-api/commit/3917fd8da20d67f916bb4a711799d897dca85322 for an example use case.  But we don't yet have a concrete API for enabling daisy chaining or presentation to multiple displays with one user gesture.  So for now limiting the controlling side of the API in a presentation context seems reasonable.

Re: Fullscreen API

I am not sure we should guarantee the presentation is started in fullscreen.  The presentation display may be a PC running a windowing system, or I could forsee a side-by-side or picture-in-picture presentation modes for some displays.

Because the current fullscreen API spec does not allow content to go fullscreen without a user gesture [1], it will require some changes to support a presentation document fullscreening itself.

It seems like the main benefit to supporting fullsreen would be reuse of style sheets that expect to be used in a fullscreen mode (and have selectors for `::fullscreen` or `::backdrop`).  Do we think it's worth it to force the presentation into fullscreen (even if it might not be rendered edge-to-edge in all cases)?

**Comment by tidoust** [comment]
See relevant discussion at TPAC F2F:
http://www.w3.org/2015/10/28-webscreens-minutes.html#item05

**RESOLUTION**: For issue #99, add a section to the spec that defines the behaviour of these APIs in the presenting context, investigate possible reuse of :fullscreen pseudo-class (discussing with CSS people)

**Comment by annevk** [comment]
Reuse of :fullscreen should be discussed here: https://github.com/whatwg/fullscreen/issues

Monkey patching the methods in OP should probably be discussed here: https://github.com/whatwg/html/issues and the correct CSSWG repository. I guess we could set some kind of flag on the environment settings object that would cause these methods to throw (or simply return) when set.

**Comment by anawhj** [comment]
I discussed a couple of CSS issues with @mfoltzgoogle, and delivered the issues in CSS WG as follows.

**New requirements for media queries from Second Screen WG**
https://lists.w3.org/Archives/Public/www-style/2015Dec/0017.html
https://lists.w3.org/Archives/Public/www-style/2015Dec/0031.html
* Summary:
  - media types were deprecated like media="tv", but there is no replacement
  - need to come up with new MQs to support second screen scenarios
  - pointer MQ for a non-interactive secondary display

**[selectors4] Why hasn't the fullscreen pseudo-class picked up?**
https://lists.w3.org/Archives/Public/www-style/2016Jan/0037.html
https://lists.w3.org/Archives/Public/www-style/2016Jan/0039.html
* Summary:
  - Fullscreen API is mostly focused on fullscreening an element
  - fullscreen pseudo-class is covered in whatwg - https://github.com/whatwg/html/issues
  - might be okay to go fullscreen on the second screen for a particular element without user interaction

**Comment by tidoust** [comment]
Discussed at the F2F:
http://www.w3.org/2016/05/24-webscreens-minutes.html#item16

Regarding methods identified at the beginning of the issue:
**PROPOSED RESOLUTION:** For methods that would require user input, add informative guidance to UAs about the need to handle them carefully.

Regarding CSS properties and media queries:
**PROPOSED RESOLUTION:** No change to the Presentation API, feature would be addressed by the CSS WG if a strong use case motivates it. Open another issue about recommending to add "TV" to the User-Agent string.

**Comment by mfoltzgoogle** [comment]
@sicking Jonas, I wanted to touch on the second resolution, which you suggested in the minutes of the F2F.

* Are you suggesting that the Presentation API spec recommend that the receiving user agent append the string "tv" to `navigator.userAgent` if it was rendering on a television?
* How would we define "television"?  Is the criterion typical viewing distance or pixel density?
* If rendering in 1-UA mode, would the user agent provide a different value for `navigator.userAgent` in the receiving browsing context vs the controlling browsing context?

In response, were you thinking the Web developer would query for "tv" in `navigator.userAgent` and provide different styling, or would the receiving user agent answer an existing CSS Media Query in a specific way?

Perhaps a pull request would clarify what you are thinking of for the Presentation API spec.

--

One thought I had was to use the `resolution` media query [1] that selects on pixel density.  Here are some resolutions for a range of TV sizes you can buy today.  Most other screens (laptops, mobiles) seem to fall into 40-140 ppcm [1] so there's not a great deal of overlap.

```
102 cm diagonal (40") @ 2160p: 43 pixels per cm
191 cm (75") @ 1080p: 12 ppcm
```

[1] https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#resolution
[2] http://dpi.lv/

**Comment by anssiko** [comment]
#305 fixed the CR blocker part of the issue, namely:

> PROPOSED RESOLUTION: For methods that would require user input, add informative guidance to UAs about the need to handle them carefully.

I think @sicking might be unavailable for a while, so I'd leave the another part of the issue open to discuss CSS properties and media queries related matters (not blocking CR):

>PROPOSED RESOLUTION: No change to the Presentation API, feature would be addressed by the CSS WG if a strong use case motivates it. Open another issue about recommending to add "TV" to the User-Agent string.

**Comment by mfoltzgoogle** [comment]
I believe Issue #303 handles one action this WG may take regarding the second proposed resolution (a proposal to add "TV" to the user agent string).

Adding media quer(y|ies) for this scenario seems to be in the hands of the CSS WG and the comments linked above in https://github.com/w3c/presentation-api/issues/99#issuecomment-221370990 were inconclusive as far as what direction that would take.

It seems like we would need to define specific capabilities manifested by various presentation displays that content authors would want to know, and that's a question for content authors.   The WG could canvass the content authors we know and draft a requirements document to take to the CSS WG (as a separate issue/work item).

Given that, I'd be okay closing this issue.

**Comment by anssiko** [comment]
Hearing no concerns with @mfoltzgoogle's proposal, I'll consider this issue closed.
